from __future__ import annotations

from datetime import datetime, timezone
from uuid import uuid4

from sqlalchemy import delete, func, select, update
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from ..orm import (
    AgentRunLogRow,
    AssignmentRow,
    ClarificationQuestionRow,
    CommentRow,
    CommitmentRow,
    ConflictRow,
    ConstraintRow,
    DecisionRow,
    DeliverableRow,
    DeliverySummaryRow,
    DissentRow,
    EventRow,
    GatedProposalRow,
    HandoffRow,
    GoalRow,
    IMSuggestionRow,
    IntakeEventRow,
    KbFolderRow,
    KbItemLicenseRow,
    KbItemRow,
    LicenseAuditRow,
    MeetingTranscriptRow,
    MembraneSubscriptionRow,
    MessageRow,
    MilestoneRow,
    NotificationRow,
    OnboardingStateRow,
    OrganizationMemberRow,
    OrganizationRow,
    ProjectMemberRow,
    ProjectRow,
    RequirementRow,
    RiskRow,
    RoutedSignalRow,
    ScrimmageRow,
    SessionRow,
    StatusTransitionRow,
    StreamMemberRow,
    StreamRow,
    TaskDependencyRow,
    TaskRow,
    TaskScoreRow,
    TaskStatusUpdateRow,
    UserRow,
    VoteRow,
)
from ..orm import SilentConsensusRow


from ._base import DuplicateIntakeError, InvalidProposalStateError, _new_id


class RequirementRepository:
    """Reads + appends versioned requirement rows (Phase 4, decision 1E).

    v1 is written by IntakeRepository at intake time. v2+ is written by
    ClarificationService after a clarify-reply merges answers back into the
    requirement. Old versions are never mutated — event history stays intact.
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def latest_for_project(self, project_id: str) -> RequirementRow | None:
        stmt = (
            select(RequirementRow)
            .where(RequirementRow.project_id == project_id)
            .order_by(RequirementRow.version.desc())
            .limit(1)
        )
        return (await self._session.execute(stmt)).scalar_one_or_none()

    async def get(self, requirement_id: str) -> RequirementRow | None:
        return (
            await self._session.execute(
                select(RequirementRow).where(RequirementRow.id == requirement_id)
            )
        ).scalar_one_or_none()

    async def append_version(
        self,
        *,
        project_id: str,
        raw_text: str,
        parsed_json: dict | None = None,
        parse_outcome: str | None = None,
        parsed_at: datetime | None = None,
    ) -> RequirementRow:
        """Write the next version row. Caller sets parsed_* after agent runs."""
        latest = await self.latest_for_project(project_id)
        next_version = (latest.version + 1) if latest else 1
        row = RequirementRow(
            id=_new_id(),
            project_id=project_id,
            version=next_version,
            raw_text=raw_text,
            parsed_json=parsed_json,
            parse_outcome=parse_outcome,
            parsed_at=parsed_at,
        )
        self._session.add(row)
        await self._session.flush()
        return row



class ClarificationQuestionRepository:
    """Append questions generated by the ClarificationAgent; record answers.

    Questions are ordered within a requirement version via `position`. The
    (requirement_id, position) pair is unique, which also makes idempotent
    re-generation safe — callers can write in a single flush.
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def append_batch(
        self, *, requirement_id: str, questions: list[str]
    ) -> list[ClarificationQuestionRow]:
        rows: list[ClarificationQuestionRow] = []
        for idx, q in enumerate(questions):
            row = ClarificationQuestionRow(
                id=_new_id(),
                requirement_id=requirement_id,
                position=idx,
                question=q,
            )
            rows.append(row)
            self._session.add(row)
        await self._session.flush()
        return rows

    async def list_for_requirement(
        self, requirement_id: str
    ) -> list[ClarificationQuestionRow]:
        stmt = (
            select(ClarificationQuestionRow)
            .where(ClarificationQuestionRow.requirement_id == requirement_id)
            .order_by(ClarificationQuestionRow.position)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def get(self, question_id: str) -> ClarificationQuestionRow | None:
        stmt = select(ClarificationQuestionRow).where(
            ClarificationQuestionRow.id == question_id
        )
        return (await self._session.execute(stmt)).scalar_one_or_none()

    async def record_answer(
        self, *, question_id: str, answer: str
    ) -> ClarificationQuestionRow | None:
        row = await self.get(question_id)
        if row is None:
            return None
        row.answer = answer
        row.answered_at = datetime.now(timezone.utc)
        await self._session.flush()
        return row

    async def unanswered_count(self, requirement_id: str) -> int:
        rows = await self.list_for_requirement(requirement_id)
        return sum(1 for r in rows if r.answer is None)



class ProjectGraphRepository:
    """Reads + appends Goal/Deliverable/Constraint/Risk rows per requirement version.

    Per decision 1E, each requirement version owns its own set of graph entities.
    v2's entities are written alongside v2 (not by mutating v1's rows). The
    "latest graph" for stage derivation is the entities bound to the latest
    requirement version. Old versions stay as history.

    append_for_requirement is idempotent — a second call for the same
    requirement_id is a no-op that returns the existing rows. Callers force
    regeneration by promoting to a new requirement version, not by rewriting.
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def _list(
        self, model, requirement_id: str
    ) -> list:
        stmt = (
            select(model)
            .where(model.requirement_id == requirement_id)
            .order_by(model.sort_order)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_goals(self, requirement_id: str) -> list[GoalRow]:
        return await self._list(GoalRow, requirement_id)

    async def list_deliverables(self, requirement_id: str) -> list[DeliverableRow]:
        return await self._list(DeliverableRow, requirement_id)

    async def list_constraints(self, requirement_id: str) -> list[ConstraintRow]:
        return await self._list(ConstraintRow, requirement_id)

    async def list_risks(self, requirement_id: str) -> list[RiskRow]:
        return await self._list(RiskRow, requirement_id)

    async def list_all(
        self, requirement_id: str
    ) -> dict[str, list]:
        return {
            "goals": await self.list_goals(requirement_id),
            "deliverables": await self.list_deliverables(requirement_id),
            "constraints": await self.list_constraints(requirement_id),
            "risks": await self.list_risks(requirement_id),
        }

    async def has_entities(self, requirement_id: str) -> bool:
        """Cheap existence check used by stage derivation."""
        for model in (GoalRow, DeliverableRow, ConstraintRow, RiskRow):
            stmt = select(model.id).where(model.requirement_id == requirement_id).limit(1)
            if (await self._session.execute(stmt)).scalar_one_or_none() is not None:
                return True
        return False

    async def append_for_requirement(
        self,
        *,
        project_id: str,
        requirement_id: str,
        goals: list[dict],
        deliverables: list[dict],
        constraints: list[dict],
        risks: list[dict],
    ) -> dict[str, list]:
        """Write the graph for a requirement version. Idempotent per requirement.

        Each entity dict carries type-specific fields:
          goal: {title, description?, success_criteria?}
          deliverable: {title, kind?}
          constraint: {kind, content, severity?}
          risk: {title, content?, severity?}
        """
        if await self.has_entities(requirement_id):
            return await self.list_all(requirement_id)

        created: dict[str, list] = {
            "goals": [],
            "deliverables": [],
            "constraints": [],
            "risks": [],
        }
        for idx, g in enumerate(goals):
            row = GoalRow(
                id=_new_id(),
                project_id=project_id,
                requirement_id=requirement_id,
                sort_order=idx,
                title=g["title"],
                description=g.get("description", ""),
                success_criteria=g.get("success_criteria"),
            )
            self._session.add(row)
            created["goals"].append(row)
        for idx, d in enumerate(deliverables):
            row = DeliverableRow(
                id=_new_id(),
                project_id=project_id,
                requirement_id=requirement_id,
                sort_order=idx,
                title=d["title"],
                kind=d.get("kind", "feature"),
            )
            self._session.add(row)
            created["deliverables"].append(row)
        for idx, c in enumerate(constraints):
            row = ConstraintRow(
                id=_new_id(),
                project_id=project_id,
                requirement_id=requirement_id,
                sort_order=idx,
                kind=c["kind"],
                content=c["content"],
                severity=c.get("severity", "medium"),
            )
            self._session.add(row)
            created["constraints"].append(row)
        for idx, r in enumerate(risks):
            row = RiskRow(
                id=_new_id(),
                project_id=project_id,
                requirement_id=requirement_id,
                sort_order=idx,
                title=r["title"],
                content=r.get("content", ""),
                severity=r.get("severity", "medium"),
            )
            self._session.add(row)
            created["risks"].append(row)
        await self._session.flush()
        return created



class PlanRepository:
    """Append + list Tasks / Dependencies / Milestones for a requirement version.

    Idempotent per requirement_id — a second append call for a requirement
    that already has tasks is a no-op. Callers promote the requirement
    version to force a rebuild.

    DAG invariants (orphan-deliverable detection, cycle detection) live in
    PlanningService — this repository is pure storage. It does own the
    minimal helpers needed to feed detection (task_refs_for_requirement,
    edge_set_for_requirement).
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def list_tasks(self, requirement_id: str) -> list[TaskRow]:
        stmt = (
            select(TaskRow)
            .where(TaskRow.requirement_id == requirement_id)
            .order_by(TaskRow.sort_order)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_dependencies(
        self, requirement_id: str
    ) -> list[TaskDependencyRow]:
        stmt = (
            select(TaskDependencyRow)
            .where(TaskDependencyRow.requirement_id == requirement_id)
            .order_by(TaskDependencyRow.created_at)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_milestones(self, requirement_id: str) -> list[MilestoneRow]:
        stmt = (
            select(MilestoneRow)
            .where(MilestoneRow.requirement_id == requirement_id)
            .order_by(MilestoneRow.sort_order)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_all(self, requirement_id: str) -> dict[str, list]:
        return {
            "tasks": await self.list_tasks(requirement_id),
            "dependencies": await self.list_dependencies(requirement_id),
            "milestones": await self.list_milestones(requirement_id),
        }

    async def has_plan(self, requirement_id: str) -> bool:
        stmt = (
            select(TaskRow.id)
            .where(TaskRow.requirement_id == requirement_id)
            .limit(1)
        )
        return (await self._session.execute(stmt)).scalar_one_or_none() is not None

    async def get_task(self, task_id: str) -> TaskRow | None:
        return (
            await self._session.execute(
                select(TaskRow).where(TaskRow.id == task_id)
            )
        ).scalar_one_or_none()

    async def list_personal_for_owner(
        self, *, project_id: str, owner_user_id: str, limit: int = 200
    ) -> list[TaskRow]:
        """Personal-scope tasks belonging to one user in one project.

        Used by the TasksPanel "My drafts" section so the owner can
        see and promote their own self-set tasks. Other members
        cannot see these.
        """
        stmt = (
            select(TaskRow)
            .where(TaskRow.project_id == project_id)
            .where(TaskRow.scope == "personal")
            .where(TaskRow.owner_user_id == owner_user_id)
            .order_by(TaskRow.created_at.desc())
            .limit(limit)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def create_personal_task(
        self,
        *,
        project_id: str,
        owner_user_id: str,
        title: str,
        description: str = "",
        source_message_id: str | None = None,
        estimate_hours: int | None = None,
        assignee_role: str = "unknown",
    ) -> TaskRow:
        """Self-set personal task. requirement_id stays NULL until
        promoted; sort_order is timestamp-based (ms since epoch
        modulo a day's worth) so it stays roughly chronological
        without coordinating with the plan's sort_order space.

        `estimate_hours` and `assignee_role` are optional at create
        time. Passing them lets the membrane's task_promote review
        run a meaningful estimate-overflow check at promote time;
        omitting them keeps the legacy behavior (NULL estimate, role
        defaults to 'unknown' so the missing_owner advisory doesn't
        fire on the candidate itself).
        """
        sort_seed = int(datetime.now(timezone.utc).timestamp() * 1000) % (
            24 * 60 * 60 * 1000
        )
        row = TaskRow(
            id=_new_id(),
            project_id=project_id,
            requirement_id=None,
            sort_order=sort_seed,
            deliverable_id=None,
            title=title,
            description=description or "",
            assignee_role=assignee_role or "unknown",
            estimate_hours=estimate_hours,
            acceptance_criteria=None,
            scope="personal",
            owner_user_id=owner_user_id,
            source_message_id=source_message_id,
            status="open",
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def promote_personal_to_plan(
        self,
        *,
        task_id: str,
        requirement_id: str,
        sort_order: int,
    ) -> TaskRow | None:
        """Personal → plan. Caller (PlanningService / TaskService)
        decides the sort_order to avoid collisions with the existing
        plan layout. Returns None if task wasn't personal.
        """
        row = await self.get_task(task_id)
        if row is None or row.scope != "personal":
            return None
        row.scope = "plan"
        row.requirement_id = requirement_id
        row.sort_order = sort_order
        await self._session.flush()
        return row

    async def append_plan(
        self,
        *,
        project_id: str,
        requirement_id: str,
        tasks: list[dict],
        dependencies: list[dict],
        milestones: list[dict],
    ) -> dict[str, list]:
        """Persist a validated plan. Idempotent per requirement.

        Caller responsibilities (PlanningService enforces):
          - task dicts carry a local `ref` for dependency resolution; this
            repository maps `ref` → generated id internally.
          - dependency dicts use `from_ref`/`to_ref`; cycle detection already
            ran.
          - every task.deliverable_ref is null or a valid deliverable id for
            this requirement (orphan check already ran).
        """
        if await self.has_plan(requirement_id):
            return await self.list_all(requirement_id)

        ref_to_id: dict[str, str] = {}
        task_rows: list[TaskRow] = []
        for idx, t in enumerate(tasks):
            row_id = _new_id()
            ref_to_id[t["ref"]] = row_id
            row = TaskRow(
                id=row_id,
                project_id=project_id,
                requirement_id=requirement_id,
                sort_order=idx,
                deliverable_id=t.get("deliverable_id"),
                title=t["title"],
                description=t.get("description", ""),
                assignee_role=t.get("assignee_role", "unknown"),
                estimate_hours=t.get("estimate_hours"),
                acceptance_criteria=t.get("acceptance_criteria"),
            )
            self._session.add(row)
            task_rows.append(row)

        dep_rows: list[TaskDependencyRow] = []
        for d in dependencies:
            from_id = ref_to_id[d["from_ref"]]
            to_id = ref_to_id[d["to_ref"]]
            row = TaskDependencyRow(
                id=_new_id(),
                requirement_id=requirement_id,
                from_task_id=from_id,
                to_task_id=to_id,
            )
            self._session.add(row)
            dep_rows.append(row)

        milestone_rows: list[MilestoneRow] = []
        for idx, m in enumerate(milestones):
            related_ids = [ref_to_id[r] for r in m.get("related_task_refs", []) if r in ref_to_id]
            row = MilestoneRow(
                id=_new_id(),
                project_id=project_id,
                requirement_id=requirement_id,
                sort_order=idx,
                title=m["title"],
                target_date=m.get("target_date"),
                related_task_ids=related_ids or None,
            )
            self._session.add(row)
            milestone_rows.append(row)

        await self._session.flush()
        return {
            "tasks": task_rows,
            "dependencies": dep_rows,
            "milestones": milestone_rows,
        }



class AssignmentRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def set_assignment(
        self, *, project_id: str, task_id: str, user_id: str | None
    ) -> AssignmentRow | None:
        """Replace any active assignment for task_id. `user_id=None` unassigns."""
        stmt = select(AssignmentRow).where(
            AssignmentRow.task_id == task_id, AssignmentRow.active == True  # noqa: E712
        )
        active = list((await self._session.execute(stmt)).scalars().all())
        now = datetime.now(timezone.utc)
        for row in active:
            row.active = False
            row.resolved_at = now

        if user_id is None:
            await self._session.flush()
            return None

        row = AssignmentRow(
            id=_new_id(),
            project_id=project_id,
            task_id=task_id,
            user_id=user_id,
            active=True,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def active_for_task(self, task_id: str) -> AssignmentRow | None:
        stmt = select(AssignmentRow).where(
            AssignmentRow.task_id == task_id, AssignmentRow.active == True  # noqa: E712
        )
        return (await self._session.execute(stmt)).scalar_one_or_none()

    async def list_for_project(self, project_id: str) -> list[AssignmentRow]:
        stmt = (
            select(AssignmentRow)
            .where(
                AssignmentRow.project_id == project_id,
                AssignmentRow.active == True,  # noqa: E712
            )
            .order_by(AssignmentRow.created_at)
        )
        return list((await self._session.execute(stmt)).scalars().all())



class TaskStatusUpdateRepository:
    """Append-only audit log. No update / delete — every status flip
    writes a fresh row. The TaskRow itself carries the current status;
    this gives the timeline."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def append(
        self,
        *,
        task_id: str,
        actor_user_id: str,
        old_status: str | None,
        new_status: str,
        note: str | None = None,
    ) -> TaskStatusUpdateRow:
        row = TaskStatusUpdateRow(
            id=_new_id(),
            task_id=task_id,
            actor_user_id=actor_user_id,
            old_status=old_status,
            new_status=new_status,
            note=note,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def list_for_task(
        self, task_id: str, *, limit: int = 50
    ) -> list[TaskStatusUpdateRow]:
        stmt = (
            select(TaskStatusUpdateRow)
            .where(TaskStatusUpdateRow.task_id == task_id)
            .order_by(TaskStatusUpdateRow.created_at.asc())
            .limit(limit)
        )
        return list((await self._session.execute(stmt)).scalars().all())



class TaskScoreRepository:
    """One score per (task, assignee). Re-scoring updates in place."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def upsert(
        self,
        *,
        task_id: str,
        reviewer_user_id: str,
        assignee_user_id: str,
        quality: str,
        feedback: str | None = None,
    ) -> tuple[TaskScoreRow, bool]:
        """Returns (row, created). created=True if this is a new score."""
        existing = (
            await self._session.execute(
                select(TaskScoreRow)
                .where(TaskScoreRow.task_id == task_id)
                .where(TaskScoreRow.assignee_user_id == assignee_user_id)
            )
        ).scalar_one_or_none()
        if existing is not None:
            existing.reviewer_user_id = reviewer_user_id
            existing.quality = quality
            existing.feedback = feedback
            existing.updated_at = datetime.now(timezone.utc)
            await self._session.flush()
            return existing, False
        row = TaskScoreRow(
            id=_new_id(),
            task_id=task_id,
            reviewer_user_id=reviewer_user_id,
            assignee_user_id=assignee_user_id,
            quality=quality,
            feedback=feedback,
        )
        self._session.add(row)
        await self._session.flush()
        return row, True

    async def get_for_task(self, task_id: str) -> TaskScoreRow | None:
        return (
            await self._session.execute(
                select(TaskScoreRow).where(TaskScoreRow.task_id == task_id)
            )
        ).scalar_one_or_none()

    async def list_for_assignee_in_window(
        self,
        *,
        assignee_user_id: str,
        project_id: str | None = None,
        since: datetime | None = None,
    ) -> list[TaskScoreRow]:
        """Used by perf_aggregation. If project_id is set, joins through
        TaskRow to filter."""
        stmt = select(TaskScoreRow).where(
            TaskScoreRow.assignee_user_id == assignee_user_id
        )
        if since is not None:
            stmt = stmt.where(TaskScoreRow.updated_at >= since)
        if project_id is not None:
            stmt = stmt.join(TaskRow, TaskScoreRow.task_id == TaskRow.id).where(
                TaskRow.project_id == project_id
            )
        return list((await self._session.execute(stmt)).scalars().all())



class StatusTransitionRepository:
    """Append-only log of graph-entity status mutations.

    Every status flip on a task / risk / deliverable / goal / milestone /
    constraint / decision writes a row here. `GET /projects/{id}/graph-at`
    replays the log to reconstruct the status of each entity at a past
    timestamp. Writes are cheap (one INSERT per mutation) and the replay
    query is `project_id + changed_at <= ts` — both indexed.

    `record` is a helper that services call after they flip a status. It
    accepts `old_status` explicitly rather than reading it back from the
    row because most service call sites already have the previous value in
    hand (they just read it before writing), and a separate read would
    double the query count on the hot path.
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def record(
        self,
        *,
        project_id: str,
        entity_kind: str,
        entity_id: str,
        old_status: str | None,
        new_status: str,
        changed_by_user_id: str | None = None,
        trace_id: str | None = None,
        changed_at: datetime | None = None,
    ) -> StatusTransitionRow:
        row = StatusTransitionRow(
            id=_new_id(),
            project_id=project_id,
            entity_kind=entity_kind,
            entity_id=entity_id,
            old_status=old_status,
            new_status=new_status,
            changed_by_user_id=changed_by_user_id,
            trace_id=trace_id,
            changed_at=changed_at or datetime.now(timezone.utc),
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def list_for_project_up_to(
        self, project_id: str, *, upto: datetime
    ) -> list[StatusTransitionRow]:
        """All transitions on or before `upto`, ordered oldest → newest.

        Ordering matters for replay: the LATEST transition wins per entity.
        A consumer iterates forwards and overwrites a running map so the
        final map carries the most recent status per entity.
        """
        stmt = (
            select(StatusTransitionRow)
            .where(
                StatusTransitionRow.project_id == project_id,
                StatusTransitionRow.changed_at <= upto,
            )
            .order_by(StatusTransitionRow.changed_at)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_for_project_since(
        self, project_id: str, *, since: datetime, limit: int = 500
    ) -> list[StatusTransitionRow]:
        """Recent transitions after `since`, oldest → newest, capped.

        Used by the web timeline strip to render event markers.
        """
        stmt = (
            select(StatusTransitionRow)
            .where(
                StatusTransitionRow.project_id == project_id,
                StatusTransitionRow.changed_at > since,
            )
            .order_by(StatusTransitionRow.changed_at)
            .limit(limit)
        )
        return list((await self._session.execute(stmt)).scalars().all())


