"""Demo data hygiene — drop duplicated seed batches from a project's
team-room stream.

The demo seed scripts (`seed_moonshot_zh.py` etc.) post a fixed set of
chat messages to the project's team-room stream. Re-running the seed
without first wiping the DB inserts a second batch with identical
`(stream_id, author_id, body)` tuples but new ids — the team-room view
then shows every line twice. Running it four times shows it four times.
That's the noise we found in the 2026-05-06 dogfood.

This script removes those duplicate rows in place: keep the earliest
`created_at` per `(stream_id, author_id, body)` group, delete the rest.

Conservative defaults:
- Dry-run unless `--apply`.
- Only the project's main team-room stream (`type='project'`). Room and
  personal streams are skipped unless `--include-rooms` is passed.
- System / action message kinds (membrane-review, edge-*, routed-*,
  vote-*) are kept even when their bodies match — they can carry state
  the FE renders. Pass `--include-system` to override.

Usage:
    uv run python scripts/demo/dedupe_team_room.py \\
        --project-id e749cfad-304f-436e-843e-04df8e1f3355 \\
        --db /data/workgraph.db

Add `--apply` to actually delete. Without it the script prints the
diff and exits.
"""
from __future__ import annotations

import argparse
import os
import sqlite3
import sys
from collections import defaultdict
from typing import Iterable


# --- defaults ---------------------------------------------------------------

# Prod docker bind path. Override via --db or WORKGRAPH_DB_PATH env.
DEFAULT_DB_PATH = os.environ.get(
    "WORKGRAPH_DB_PATH", "/data/workgraph.db"
)

# Stream types we touch by default. The team-room stream is `type='project'`
# per packages/persistence/.../orm.py's StreamRow schema (legacy name kept
# per north-star Correction R "no schema rename"). `room` is the per-team-
# subset stream; `personal` is each user's private thread; `dm` is direct
# message. Cleaning rooms/personal risks deleting evidence-trail rows users
# generated by clicking buttons twice — opt in with --include-rooms.
DEFAULT_STREAM_TYPES = ("project",)
ROOMS_STREAM_TYPES = ("project", "room")

# Message kinds whose bodies often look duplicate-ish but actually carry
# state the FE renders: each is a separate suggestion card / vote / tool
# round-trip. Skip by default. Per user spec (2026-05-06 PM dogfood).
SYSTEM_KINDS = frozenset(
    {
        "membrane-review",
        "routed-inbound",
        "routed-reply",
        "edge-answer",
        "edge-clarify",
        "edge-route-proposal",
        "edge-tool-call",
        "edge-tool-result",
        "vote-opened",
        "vote-resolved-approved",
        "vote-resolved-denied",
    }
)


# --- core -------------------------------------------------------------------


def find_duplicates(
    conn: sqlite3.Connection,
    *,
    project_id: str,
    stream_types: Iterable[str],
    include_system: bool,
) -> dict[tuple[str, str, str], list[tuple[str, str, str]]]:
    """Return `{(stream_id, author_id, body): [(msg_id, created_at, kind), ...]}`
    for every group with > 1 row. Per group the list is ordered by
    `created_at ASC` so the FIRST entry is the keeper.

    System-kind rows (per SYSTEM_KINDS) are filtered out unless
    `include_system` is True — they can be near-duplicates that carry
    distinct state across rows.
    """
    placeholders = ",".join("?" * len(list(stream_types)))
    stream_types_list = list(stream_types)
    cur = conn.execute(
        f"""
        SELECT m.id, m.stream_id, m.author_id, m.body, m.created_at, m.kind
          FROM messages m
          JOIN streams s ON s.id = m.stream_id
         WHERE s.project_id = ?
           AND s.type IN ({placeholders})
         ORDER BY m.created_at ASC
        """,
        (project_id, *stream_types_list),
    )
    groups: dict[tuple[str, str, str], list[tuple[str, str, str]]] = defaultdict(
        list
    )
    for row in cur.fetchall():
        msg_id, stream_id, author_id, body, created_at, kind = row
        if not include_system and (kind or "") in SYSTEM_KINDS:
            continue
        key = (stream_id, author_id or "", body or "")
        groups[key].append((msg_id, created_at, kind or ""))
    return {k: v for k, v in groups.items() if len(v) > 1}


def render_dry_run(
    groups: dict[tuple[str, str, str], list[tuple[str, str, str]]],
) -> tuple[int, int]:
    """Pretty-print the duplicate diff. Returns (groups, rows_to_delete)."""
    if not groups:
        print("No duplicates found in scope.")
        return 0, 0

    rows_to_delete = 0
    for (stream_id, author_id, body), rows in sorted(
        groups.items(), key=lambda kv: -len(kv[1])
    ):
        rows_to_delete += len(rows) - 1
        preview = body.replace("\n", " ")
        if len(preview) > 80:
            preview = preview[:77] + "…"
        print()
        print(f"stream={stream_id[:8]}…  author={author_id[:8]}…  ×{len(rows)}")
        print(f"    body: {preview!r}")
        keeper_id, keeper_at, keeper_kind = rows[0]
        print(f"    KEEP  {keeper_id[:8]}… @ {keeper_at}  kind={keeper_kind}")
        for dup_id, dup_at, dup_kind in rows[1:]:
            print(f"    drop  {dup_id[:8]}… @ {dup_at}  kind={dup_kind}")
    return len(groups), rows_to_delete


def apply_deletes(
    conn: sqlite3.Connection,
    groups: dict[tuple[str, str, str], list[tuple[str, str, str]]],
) -> int:
    """Delete every row but the keeper in each group. Returns deleted count.

    Single transaction; if any DELETE fails the whole pass rolls back. We
    don't touch attachments — the seed messages are pure text so there's
    no orphaned blob risk.
    """
    delete_ids: list[str] = []
    for rows in groups.values():
        for msg_id, _ts, _kind in rows[1:]:
            delete_ids.append(msg_id)
    if not delete_ids:
        return 0
    placeholders = ",".join("?" * len(delete_ids))
    conn.execute(
        f"DELETE FROM messages WHERE id IN ({placeholders})",
        delete_ids,
    )
    conn.commit()
    return len(delete_ids)


# --- entrypoint -------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Drop duplicate seed messages from a project's team room.",
    )
    parser.add_argument(
        "--project-id",
        required=True,
        help="Project UUID. Only this project's streams are touched.",
    )
    parser.add_argument(
        "--db",
        default=DEFAULT_DB_PATH,
        help=(
            "SQLite DB file path. Default: $WORKGRAPH_DB_PATH or "
            f"{DEFAULT_DB_PATH}."
        ),
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Actually delete. Without this flag, the script is a dry-run.",
    )
    parser.add_argument(
        "--include-rooms",
        action="store_true",
        help=(
            "Also consider per-team `room` streams. Default: only the main "
            "`project` (team room) stream."
        ),
    )
    parser.add_argument(
        "--include-system",
        action="store_true",
        help=(
            "Include system / action message kinds (membrane-review, edge-*, "
            "routed-*, vote-*) in dedupe candidates. Default: skip them — "
            "they often carry per-row state even when bodies match."
        ),
    )
    args = parser.parse_args(argv)

    if not os.path.exists(args.db):
        print(f"DB file not found: {args.db}", file=sys.stderr)
        return 2

    stream_types = ROOMS_STREAM_TYPES if args.include_rooms else DEFAULT_STREAM_TYPES

    print(f"DB:         {args.db}")
    print(f"Project:    {args.project_id}")
    print(f"Streams:    {', '.join(stream_types)}")
    print(f"System:     {'INCLUDED' if args.include_system else 'skipped'}")
    print(f"Mode:       {'APPLY' if args.apply else 'dry-run'}")

    conn = sqlite3.connect(args.db)
    try:
        groups = find_duplicates(
            conn,
            project_id=args.project_id,
            stream_types=stream_types,
            include_system=args.include_system,
        )
        n_groups, n_rows = render_dry_run(groups)
        print()
        print(f"--- summary: {n_groups} duplicate groups, {n_rows} rows to delete")

        if args.apply and n_rows > 0:
            deleted = apply_deletes(conn, groups)
            print(f"--- deleted {deleted} rows. DONE.")
        elif args.apply:
            print("--- nothing to delete.")
        else:
            print("--- dry-run only. Pass --apply to actually delete.")
    finally:
        conn.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
