from __future__ import annotations

from datetime import datetime, timezone
from uuid import uuid4

from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from .orm import (
    AgentRunLogRow,
    AssignmentRow,
    ClarificationQuestionRow,
    CommentRow,
    ConflictRow,
    ConstraintRow,
    DecisionRow,
    DeliverableRow,
    DeliverySummaryRow,
    EventRow,
    GoalRow,
    IMSuggestionRow,
    IntakeEventRow,
    MessageRow,
    MilestoneRow,
    NotificationRow,
    ProjectMemberRow,
    ProjectRow,
    RequirementRow,
    RiskRow,
    SessionRow,
    TaskDependencyRow,
    TaskRow,
    UserRow,
)


class DuplicateIntakeError(Exception):
    """Raised when (source, source_event_id) already exists."""

    def __init__(self, source: str, source_event_id: str, existing_project_id: str) -> None:
        super().__init__(
            f"intake already recorded: source={source} source_event_id={source_event_id}"
        )
        self.source = source
        self.source_event_id = source_event_id
        self.existing_project_id = existing_project_id


def _new_id() -> str:
    return str(uuid4())


class IntakeRepository:
    """Creates project+requirement+intake_event atomically, deduped by source key."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def find_existing(
        self, source: str, source_event_id: str
    ) -> IntakeEventRow | None:
        stmt = select(IntakeEventRow).where(
            IntakeEventRow.source == source,
            IntakeEventRow.source_event_id == source_event_id,
        )
        return (await self._session.execute(stmt)).scalar_one_or_none()

    async def create(
        self,
        *,
        source: str,
        source_event_id: str,
        title: str,
        raw_text: str,
        payload: dict,
    ) -> tuple[ProjectRow, RequirementRow, IntakeEventRow]:
        existing = await self.find_existing(source, source_event_id)
        if existing is not None:
            raise DuplicateIntakeError(source, source_event_id, existing.project_id)

        project = ProjectRow(id=_new_id(), title=title)
        requirement = RequirementRow(
            id=_new_id(), project_id=project.id, raw_text=raw_text, version=1
        )
        intake = IntakeEventRow(
            id=_new_id(),
            source=source,
            source_event_id=source_event_id,
            project_id=project.id,
            payload=payload,
        )
        self._session.add_all([project, requirement, intake])
        try:
            await self._session.flush()
        except IntegrityError as e:
            await self._session.rollback()
            # Race: another request wrote the same source_event_id between find + flush.
            fresh = await self.find_existing(source, source_event_id)
            if fresh is not None:
                raise DuplicateIntakeError(source, source_event_id, fresh.project_id) from e
            raise
        return project, requirement, intake


class RequirementRepository:
    """Reads + appends versioned requirement rows (Phase 4, decision 1E).

    v1 is written by IntakeRepository at intake time. v2+ is written by
    ClarificationService after a clarify-reply merges answers back into the
    requirement. Old versions are never mutated — event history stays intact.
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def latest_for_project(self, project_id: str) -> RequirementRow | None:
        stmt = (
            select(RequirementRow)
            .where(RequirementRow.project_id == project_id)
            .order_by(RequirementRow.version.desc())
            .limit(1)
        )
        return (await self._session.execute(stmt)).scalar_one_or_none()

    async def append_version(
        self,
        *,
        project_id: str,
        raw_text: str,
        parsed_json: dict | None = None,
        parse_outcome: str | None = None,
        parsed_at: datetime | None = None,
    ) -> RequirementRow:
        """Write the next version row. Caller sets parsed_* after agent runs."""
        latest = await self.latest_for_project(project_id)
        next_version = (latest.version + 1) if latest else 1
        row = RequirementRow(
            id=_new_id(),
            project_id=project_id,
            version=next_version,
            raw_text=raw_text,
            parsed_json=parsed_json,
            parse_outcome=parse_outcome,
            parsed_at=parsed_at,
        )
        self._session.add(row)
        await self._session.flush()
        return row


class ClarificationQuestionRepository:
    """Append questions generated by the ClarificationAgent; record answers.

    Questions are ordered within a requirement version via `position`. The
    (requirement_id, position) pair is unique, which also makes idempotent
    re-generation safe — callers can write in a single flush.
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def append_batch(
        self, *, requirement_id: str, questions: list[str]
    ) -> list[ClarificationQuestionRow]:
        rows: list[ClarificationQuestionRow] = []
        for idx, q in enumerate(questions):
            row = ClarificationQuestionRow(
                id=_new_id(),
                requirement_id=requirement_id,
                position=idx,
                question=q,
            )
            rows.append(row)
            self._session.add(row)
        await self._session.flush()
        return rows

    async def list_for_requirement(
        self, requirement_id: str
    ) -> list[ClarificationQuestionRow]:
        stmt = (
            select(ClarificationQuestionRow)
            .where(ClarificationQuestionRow.requirement_id == requirement_id)
            .order_by(ClarificationQuestionRow.position)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def get(self, question_id: str) -> ClarificationQuestionRow | None:
        stmt = select(ClarificationQuestionRow).where(
            ClarificationQuestionRow.id == question_id
        )
        return (await self._session.execute(stmt)).scalar_one_or_none()

    async def record_answer(
        self, *, question_id: str, answer: str
    ) -> ClarificationQuestionRow | None:
        row = await self.get(question_id)
        if row is None:
            return None
        row.answer = answer
        row.answered_at = datetime.now(timezone.utc)
        await self._session.flush()
        return row

    async def unanswered_count(self, requirement_id: str) -> int:
        rows = await self.list_for_requirement(requirement_id)
        return sum(1 for r in rows if r.answer is None)


class ProjectGraphRepository:
    """Reads + appends Goal/Deliverable/Constraint/Risk rows per requirement version.

    Per decision 1E, each requirement version owns its own set of graph entities.
    v2's entities are written alongside v2 (not by mutating v1's rows). The
    "latest graph" for stage derivation is the entities bound to the latest
    requirement version. Old versions stay as history.

    append_for_requirement is idempotent — a second call for the same
    requirement_id is a no-op that returns the existing rows. Callers force
    regeneration by promoting to a new requirement version, not by rewriting.
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def _list(
        self, model, requirement_id: str
    ) -> list:
        stmt = (
            select(model)
            .where(model.requirement_id == requirement_id)
            .order_by(model.sort_order)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_goals(self, requirement_id: str) -> list[GoalRow]:
        return await self._list(GoalRow, requirement_id)

    async def list_deliverables(self, requirement_id: str) -> list[DeliverableRow]:
        return await self._list(DeliverableRow, requirement_id)

    async def list_constraints(self, requirement_id: str) -> list[ConstraintRow]:
        return await self._list(ConstraintRow, requirement_id)

    async def list_risks(self, requirement_id: str) -> list[RiskRow]:
        return await self._list(RiskRow, requirement_id)

    async def list_all(
        self, requirement_id: str
    ) -> dict[str, list]:
        return {
            "goals": await self.list_goals(requirement_id),
            "deliverables": await self.list_deliverables(requirement_id),
            "constraints": await self.list_constraints(requirement_id),
            "risks": await self.list_risks(requirement_id),
        }

    async def has_entities(self, requirement_id: str) -> bool:
        """Cheap existence check used by stage derivation."""
        for model in (GoalRow, DeliverableRow, ConstraintRow, RiskRow):
            stmt = select(model.id).where(model.requirement_id == requirement_id).limit(1)
            if (await self._session.execute(stmt)).scalar_one_or_none() is not None:
                return True
        return False

    async def append_for_requirement(
        self,
        *,
        project_id: str,
        requirement_id: str,
        goals: list[dict],
        deliverables: list[dict],
        constraints: list[dict],
        risks: list[dict],
    ) -> dict[str, list]:
        """Write the graph for a requirement version. Idempotent per requirement.

        Each entity dict carries type-specific fields:
          goal: {title, description?, success_criteria?}
          deliverable: {title, kind?}
          constraint: {kind, content, severity?}
          risk: {title, content?, severity?}
        """
        if await self.has_entities(requirement_id):
            return await self.list_all(requirement_id)

        created: dict[str, list] = {
            "goals": [],
            "deliverables": [],
            "constraints": [],
            "risks": [],
        }
        for idx, g in enumerate(goals):
            row = GoalRow(
                id=_new_id(),
                project_id=project_id,
                requirement_id=requirement_id,
                sort_order=idx,
                title=g["title"],
                description=g.get("description", ""),
                success_criteria=g.get("success_criteria"),
            )
            self._session.add(row)
            created["goals"].append(row)
        for idx, d in enumerate(deliverables):
            row = DeliverableRow(
                id=_new_id(),
                project_id=project_id,
                requirement_id=requirement_id,
                sort_order=idx,
                title=d["title"],
                kind=d.get("kind", "feature"),
            )
            self._session.add(row)
            created["deliverables"].append(row)
        for idx, c in enumerate(constraints):
            row = ConstraintRow(
                id=_new_id(),
                project_id=project_id,
                requirement_id=requirement_id,
                sort_order=idx,
                kind=c["kind"],
                content=c["content"],
                severity=c.get("severity", "medium"),
            )
            self._session.add(row)
            created["constraints"].append(row)
        for idx, r in enumerate(risks):
            row = RiskRow(
                id=_new_id(),
                project_id=project_id,
                requirement_id=requirement_id,
                sort_order=idx,
                title=r["title"],
                content=r.get("content", ""),
                severity=r.get("severity", "medium"),
            )
            self._session.add(row)
            created["risks"].append(row)
        await self._session.flush()
        return created


class PlanRepository:
    """Append + list Tasks / Dependencies / Milestones for a requirement version.

    Idempotent per requirement_id — a second append call for a requirement
    that already has tasks is a no-op. Callers promote the requirement
    version to force a rebuild.

    DAG invariants (orphan-deliverable detection, cycle detection) live in
    PlanningService — this repository is pure storage. It does own the
    minimal helpers needed to feed detection (task_refs_for_requirement,
    edge_set_for_requirement).
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def list_tasks(self, requirement_id: str) -> list[TaskRow]:
        stmt = (
            select(TaskRow)
            .where(TaskRow.requirement_id == requirement_id)
            .order_by(TaskRow.sort_order)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_dependencies(
        self, requirement_id: str
    ) -> list[TaskDependencyRow]:
        stmt = (
            select(TaskDependencyRow)
            .where(TaskDependencyRow.requirement_id == requirement_id)
            .order_by(TaskDependencyRow.created_at)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_milestones(self, requirement_id: str) -> list[MilestoneRow]:
        stmt = (
            select(MilestoneRow)
            .where(MilestoneRow.requirement_id == requirement_id)
            .order_by(MilestoneRow.sort_order)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_all(self, requirement_id: str) -> dict[str, list]:
        return {
            "tasks": await self.list_tasks(requirement_id),
            "dependencies": await self.list_dependencies(requirement_id),
            "milestones": await self.list_milestones(requirement_id),
        }

    async def has_plan(self, requirement_id: str) -> bool:
        stmt = (
            select(TaskRow.id)
            .where(TaskRow.requirement_id == requirement_id)
            .limit(1)
        )
        return (await self._session.execute(stmt)).scalar_one_or_none() is not None

    async def append_plan(
        self,
        *,
        project_id: str,
        requirement_id: str,
        tasks: list[dict],
        dependencies: list[dict],
        milestones: list[dict],
    ) -> dict[str, list]:
        """Persist a validated plan. Idempotent per requirement.

        Caller responsibilities (PlanningService enforces):
          - task dicts carry a local `ref` for dependency resolution; this
            repository maps `ref` → generated id internally.
          - dependency dicts use `from_ref`/`to_ref`; cycle detection already
            ran.
          - every task.deliverable_ref is null or a valid deliverable id for
            this requirement (orphan check already ran).
        """
        if await self.has_plan(requirement_id):
            return await self.list_all(requirement_id)

        ref_to_id: dict[str, str] = {}
        task_rows: list[TaskRow] = []
        for idx, t in enumerate(tasks):
            row_id = _new_id()
            ref_to_id[t["ref"]] = row_id
            row = TaskRow(
                id=row_id,
                project_id=project_id,
                requirement_id=requirement_id,
                sort_order=idx,
                deliverable_id=t.get("deliverable_id"),
                title=t["title"],
                description=t.get("description", ""),
                assignee_role=t.get("assignee_role", "unknown"),
                estimate_hours=t.get("estimate_hours"),
                acceptance_criteria=t.get("acceptance_criteria"),
            )
            self._session.add(row)
            task_rows.append(row)

        dep_rows: list[TaskDependencyRow] = []
        for d in dependencies:
            from_id = ref_to_id[d["from_ref"]]
            to_id = ref_to_id[d["to_ref"]]
            row = TaskDependencyRow(
                id=_new_id(),
                requirement_id=requirement_id,
                from_task_id=from_id,
                to_task_id=to_id,
            )
            self._session.add(row)
            dep_rows.append(row)

        milestone_rows: list[MilestoneRow] = []
        for idx, m in enumerate(milestones):
            related_ids = [ref_to_id[r] for r in m.get("related_task_refs", []) if r in ref_to_id]
            row = MilestoneRow(
                id=_new_id(),
                project_id=project_id,
                requirement_id=requirement_id,
                sort_order=idx,
                title=m["title"],
                target_date=m.get("target_date"),
                related_task_ids=related_ids or None,
            )
            self._session.add(row)
            milestone_rows.append(row)

        await self._session.flush()
        return {
            "tasks": task_rows,
            "dependencies": dep_rows,
            "milestones": milestone_rows,
        }


class EventRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def append(
        self, *, name: str, trace_id: str | None, payload: dict
    ) -> EventRow:
        # Surface project_id onto the column so Phase 7' SSE can filter without
        # JSON queries. Keeps the payload dict unchanged for downstream readers.
        project_id = payload.get("project_id") if isinstance(payload, dict) else None
        row = EventRow(
            id=_new_id(),
            name=name,
            trace_id=trace_id,
            payload=payload,
            project_id=project_id,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def list_by_name(self, name: str) -> list[EventRow]:
        stmt = select(EventRow).where(EventRow.name == name).order_by(EventRow.created_at)
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_for_trace(self, trace_id: str) -> list[EventRow]:
        stmt = (
            select(EventRow)
            .where(EventRow.trace_id == trace_id)
            .order_by(EventRow.created_at)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_for_project_since(
        self, project_id: str, since_id: str | None = None, limit: int = 100
    ) -> list[EventRow]:
        """Ordered by created_at. Cursor via `since_id` (exclusive)."""
        stmt = select(EventRow).where(EventRow.project_id == project_id)
        if since_id is not None:
            since = (
                await self._session.execute(
                    select(EventRow).where(EventRow.id == since_id)
                )
            ).scalar_one_or_none()
            if since is not None:
                stmt = stmt.where(EventRow.created_at > since.created_at)
        stmt = stmt.order_by(EventRow.created_at).limit(limit)
        return list((await self._session.execute(stmt)).scalars().all())


class AgentRunLogRepository:
    """Writes one row per LLM agent call — decision 2C2."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def append(
        self,
        *,
        agent: str,
        prompt_version: str,
        outcome: str,
        attempts: int,
        latency_ms: int,
        prompt_tokens: int,
        completion_tokens: int,
        cache_read_tokens: int,
        project_id: str | None = None,
        trace_id: str | None = None,
        error: str | None = None,
    ) -> AgentRunLogRow:
        row = AgentRunLogRow(
            id=_new_id(),
            agent=agent,
            prompt_version=prompt_version,
            project_id=project_id,
            trace_id=trace_id,
            outcome=outcome,
            attempts=attempts,
            latency_ms=latency_ms,
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            cache_read_tokens=cache_read_tokens,
            error=error,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def list_for_agent(self, agent: str) -> list[AgentRunLogRow]:
        stmt = (
            select(AgentRunLogRow)
            .where(AgentRunLogRow.agent == agent)
            .order_by(AgentRunLogRow.created_at)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_since(
        self,
        *,
        since: datetime | None = None,
        agent: str | None = None,
        limit: int = 500,
    ) -> list[AgentRunLogRow]:
        """Return rows created at or after `since`, optionally filtered by agent."""
        stmt = select(AgentRunLogRow)
        if since is not None:
            stmt = stmt.where(AgentRunLogRow.created_at >= since)
        if agent is not None:
            stmt = stmt.where(AgentRunLogRow.agent == agent)
        stmt = stmt.order_by(AgentRunLogRow.created_at.desc()).limit(limit)
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_for_trace(self, trace_id: str) -> list[AgentRunLogRow]:
        stmt = (
            select(AgentRunLogRow)
            .where(AgentRunLogRow.trace_id == trace_id)
            .order_by(AgentRunLogRow.created_at)
        )
        return list((await self._session.execute(stmt)).scalars().all())


# ---- Phase 7' auth + Phase 7'' collab repositories ----------------------


class UserRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(
        self,
        *,
        username: str,
        password_hash: str,
        password_salt: str,
        display_name: str = "",
    ) -> UserRow:
        row = UserRow(
            id=_new_id(),
            username=username,
            password_hash=password_hash,
            password_salt=password_salt,
            display_name=display_name or username,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def get(self, user_id: str) -> UserRow | None:
        return (
            await self._session.execute(select(UserRow).where(UserRow.id == user_id))
        ).scalar_one_or_none()

    async def get_by_username(self, username: str) -> UserRow | None:
        return (
            await self._session.execute(
                select(UserRow).where(UserRow.username == username)
            )
        ).scalar_one_or_none()

    async def list_all(self, limit: int = 50) -> list[UserRow]:
        stmt = select(UserRow).order_by(UserRow.created_at).limit(limit)
        return list((await self._session.execute(stmt)).scalars().all())


class SessionRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(
        self, *, token: str, user_id: str, expires_at: datetime
    ) -> SessionRow:
        row = SessionRow(token=token, user_id=user_id, expires_at=expires_at)
        self._session.add(row)
        await self._session.flush()
        return row

    async def get(self, token: str) -> SessionRow | None:
        return (
            await self._session.execute(
                select(SessionRow).where(SessionRow.token == token)
            )
        ).scalar_one_or_none()

    async def delete(self, token: str) -> None:
        row = await self.get(token)
        if row is not None:
            await self._session.delete(row)
            await self._session.flush()


class ProjectMemberRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def add(
        self, *, project_id: str, user_id: str, role: str = "member"
    ) -> ProjectMemberRow:
        existing = (
            await self._session.execute(
                select(ProjectMemberRow).where(
                    ProjectMemberRow.project_id == project_id,
                    ProjectMemberRow.user_id == user_id,
                )
            )
        ).scalar_one_or_none()
        if existing is not None:
            return existing
        row = ProjectMemberRow(
            id=_new_id(), project_id=project_id, user_id=user_id, role=role
        )
        self._session.add(row)
        try:
            await self._session.flush()
        except IntegrityError:
            await self._session.rollback()
            existing = (
                await self._session.execute(
                    select(ProjectMemberRow).where(
                        ProjectMemberRow.project_id == project_id,
                        ProjectMemberRow.user_id == user_id,
                    )
                )
            ).scalar_one()
            return existing
        return row

    async def list_for_project(self, project_id: str) -> list[ProjectMemberRow]:
        stmt = (
            select(ProjectMemberRow)
            .where(ProjectMemberRow.project_id == project_id)
            .order_by(ProjectMemberRow.created_at)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_for_user(self, user_id: str) -> list[ProjectMemberRow]:
        stmt = (
            select(ProjectMemberRow)
            .where(ProjectMemberRow.user_id == user_id)
            .order_by(ProjectMemberRow.created_at.desc())
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def is_member(self, project_id: str, user_id: str) -> bool:
        row = (
            await self._session.execute(
                select(ProjectMemberRow).where(
                    ProjectMemberRow.project_id == project_id,
                    ProjectMemberRow.user_id == user_id,
                )
            )
        ).scalar_one_or_none()
        return row is not None


class AssignmentRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def set_assignment(
        self, *, project_id: str, task_id: str, user_id: str | None
    ) -> AssignmentRow | None:
        """Replace any active assignment for task_id. `user_id=None` unassigns."""
        stmt = select(AssignmentRow).where(
            AssignmentRow.task_id == task_id, AssignmentRow.active == True  # noqa: E712
        )
        active = list((await self._session.execute(stmt)).scalars().all())
        now = datetime.now(timezone.utc)
        for row in active:
            row.active = False
            row.resolved_at = now

        if user_id is None:
            await self._session.flush()
            return None

        row = AssignmentRow(
            id=_new_id(),
            project_id=project_id,
            task_id=task_id,
            user_id=user_id,
            active=True,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def active_for_task(self, task_id: str) -> AssignmentRow | None:
        stmt = select(AssignmentRow).where(
            AssignmentRow.task_id == task_id, AssignmentRow.active == True  # noqa: E712
        )
        return (await self._session.execute(stmt)).scalar_one_or_none()

    async def list_for_project(self, project_id: str) -> list[AssignmentRow]:
        stmt = (
            select(AssignmentRow)
            .where(
                AssignmentRow.project_id == project_id,
                AssignmentRow.active == True,  # noqa: E712
            )
            .order_by(AssignmentRow.created_at)
        )
        return list((await self._session.execute(stmt)).scalars().all())


class CommentRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def append(
        self,
        *,
        project_id: str,
        author_id: str,
        target_kind: str,
        target_id: str,
        body: str,
        parent_comment_id: str | None = None,
    ) -> CommentRow:
        row = CommentRow(
            id=_new_id(),
            project_id=project_id,
            author_id=author_id,
            target_kind=target_kind,
            target_id=target_id,
            body=body,
            parent_comment_id=parent_comment_id,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def list_for_target(
        self, target_kind: str, target_id: str
    ) -> list[CommentRow]:
        stmt = (
            select(CommentRow)
            .where(
                CommentRow.target_kind == target_kind,
                CommentRow.target_id == target_id,
            )
            .order_by(CommentRow.created_at)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_for_project(self, project_id: str) -> list[CommentRow]:
        stmt = (
            select(CommentRow)
            .where(CommentRow.project_id == project_id)
            .order_by(CommentRow.created_at)
        )
        return list((await self._session.execute(stmt)).scalars().all())


class MessageRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def append(
        self, *, project_id: str, author_id: str, body: str
    ) -> MessageRow:
        row = MessageRow(
            id=_new_id(), project_id=project_id, author_id=author_id, body=body
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def list_recent(
        self, project_id: str, limit: int = 100
    ) -> list[MessageRow]:
        stmt = (
            select(MessageRow)
            .where(MessageRow.project_id == project_id)
            .order_by(MessageRow.created_at.desc())
            .limit(limit)
        )
        rows = list((await self._session.execute(stmt)).scalars().all())
        rows.reverse()
        return rows


class IMSuggestionRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def append(
        self,
        *,
        project_id: str,
        message_id: str,
        kind: str,
        confidence: float,
        targets: list | None,
        proposal: dict | None,
        reasoning: str,
        prompt_version: str | None,
        outcome: str,
        attempts: int,
    ) -> IMSuggestionRow:
        row = IMSuggestionRow(
            id=_new_id(),
            project_id=project_id,
            message_id=message_id,
            kind=kind,
            confidence=confidence,
            targets=targets,
            proposal=proposal,
            reasoning=reasoning,
            prompt_version=prompt_version,
            outcome=outcome,
            attempts=attempts,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def get(self, suggestion_id: str) -> IMSuggestionRow | None:
        return (
            await self._session.execute(
                select(IMSuggestionRow).where(IMSuggestionRow.id == suggestion_id)
            )
        ).scalar_one_or_none()

    async def get_for_message(self, message_id: str) -> IMSuggestionRow | None:
        return (
            await self._session.execute(
                select(IMSuggestionRow).where(
                    IMSuggestionRow.message_id == message_id
                )
            )
        ).scalar_one_or_none()

    async def resolve(self, suggestion_id: str, status: str) -> IMSuggestionRow | None:
        row = await self.get(suggestion_id)
        if row is None:
            return None
        row.status = status
        row.resolved_at = datetime.now(timezone.utc)
        await self._session.flush()
        return row


class NotificationRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def append(
        self,
        *,
        user_id: str,
        project_id: str,
        kind: str,
        body: str,
        target_kind: str | None = None,
        target_id: str | None = None,
    ) -> NotificationRow:
        row = NotificationRow(
            id=_new_id(),
            user_id=user_id,
            project_id=project_id,
            kind=kind,
            body=body,
            target_kind=target_kind,
            target_id=target_id,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def list_for_user(
        self, user_id: str, *, unread_only: bool = False, limit: int = 50
    ) -> list[NotificationRow]:
        stmt = select(NotificationRow).where(NotificationRow.user_id == user_id)
        if unread_only:
            stmt = stmt.where(NotificationRow.read == False)  # noqa: E712
        stmt = stmt.order_by(NotificationRow.created_at.desc()).limit(limit)
        return list((await self._session.execute(stmt)).scalars().all())

    async def unread_count(self, user_id: str) -> int:
        stmt = select(NotificationRow.id).where(
            NotificationRow.user_id == user_id,
            NotificationRow.read == False,  # noqa: E712
        )
        return len(list((await self._session.execute(stmt)).scalars().all()))

    async def mark_read(self, notification_id: str, user_id: str) -> NotificationRow | None:
        row = (
            await self._session.execute(
                select(NotificationRow).where(
                    NotificationRow.id == notification_id,
                    NotificationRow.user_id == user_id,
                )
            )
        ).scalar_one_or_none()
        if row is None:
            return None
        row.read = True
        await self._session.flush()
        return row

    async def mark_all_read(self, user_id: str) -> int:
        rows = await self.list_for_user(user_id, unread_only=True, limit=500)
        for r in rows:
            r.read = True
        await self._session.flush()
        return len(rows)


class ConflictRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def upsert(
        self,
        *,
        project_id: str,
        requirement_id: str | None,
        rule: str,
        severity: str,
        fingerprint: str,
        targets: list,
        detail: dict,
        trace_id: str | None = None,
    ) -> tuple[ConflictRow, bool]:
        """Insert a new conflict or reopen an existing one by fingerprint.

        Returns (row, is_new). A dismissed/resolved conflict that matches on
        fingerprint is NOT reopened — the user's decision stands. Only `open`
        or `stale` rows are refreshed.
        """
        existing = (
            await self._session.execute(
                select(ConflictRow).where(
                    ConflictRow.project_id == project_id,
                    ConflictRow.fingerprint == fingerprint,
                )
            )
        ).scalar_one_or_none()
        if existing is not None:
            if existing.status in ("open", "stale"):
                existing.status = "open"
                existing.severity = severity
                existing.targets = targets
                existing.detail = detail
                existing.requirement_id = requirement_id
                if trace_id:
                    existing.trace_id = trace_id
                await self._session.flush()
            return existing, False

        row = ConflictRow(
            id=_new_id(),
            project_id=project_id,
            requirement_id=requirement_id,
            rule=rule,
            severity=severity,
            fingerprint=fingerprint,
            targets=targets,
            detail=detail,
            trace_id=trace_id,
            status="open",
            explanation_outcome="pending",
        )
        self._session.add(row)
        await self._session.flush()
        return row, True

    async def attach_explanation(
        self,
        conflict_id: str,
        *,
        summary: str,
        options: list,
        prompt_version: str,
        outcome: str,
    ) -> ConflictRow | None:
        row = await self.get(conflict_id)
        if row is None:
            return None
        row.summary = summary
        row.options = options
        row.explanation_prompt_version = prompt_version
        row.explanation_outcome = outcome
        await self._session.flush()
        return row

    async def get(self, conflict_id: str) -> ConflictRow | None:
        return (
            await self._session.execute(
                select(ConflictRow).where(ConflictRow.id == conflict_id)
            )
        ).scalar_one_or_none()

    async def list_for_project(
        self,
        project_id: str,
        *,
        include_closed: bool = False,
    ) -> list[ConflictRow]:
        stmt = select(ConflictRow).where(ConflictRow.project_id == project_id)
        if not include_closed:
            stmt = stmt.where(ConflictRow.status == "open")
        stmt = stmt.order_by(
            ConflictRow.severity.desc(),  # "high" > "medium" > "low" alphabetically? see service for ordering map
            ConflictRow.created_at.desc(),
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_open_fingerprints(self, project_id: str) -> set[str]:
        stmt = select(ConflictRow.fingerprint).where(
            ConflictRow.project_id == project_id,
            ConflictRow.status == "open",
        )
        return set((await self._session.execute(stmt)).scalars().all())

    async def mark_stale(self, project_id: str, keep: set[str]) -> int:
        """Flip any open conflict whose fingerprint isn't in `keep` to stale.

        Called at the end of a detection pass so the UI can gray out conflicts
        that the current rules no longer fire on, without losing the history.
        """
        rows = list(
            (
                await self._session.execute(
                    select(ConflictRow).where(
                        ConflictRow.project_id == project_id,
                        ConflictRow.status == "open",
                    )
                )
            )
            .scalars()
            .all()
        )
        n = 0
        for r in rows:
            if r.fingerprint not in keep:
                r.status = "stale"
                n += 1
        if n:
            await self._session.flush()
        return n

    async def resolve(
        self,
        conflict_id: str,
        *,
        user_id: str,
        option_index: int | None,
    ) -> ConflictRow | None:
        row = await self.get(conflict_id)
        if row is None:
            return None
        row.status = "resolved"
        row.resolved_by = user_id
        row.resolved_option_index = option_index
        row.resolved_at = datetime.now(timezone.utc)
        await self._session.flush()
        return row

    async def dismiss(
        self, conflict_id: str, *, user_id: str
    ) -> ConflictRow | None:
        row = await self.get(conflict_id)
        if row is None:
            return None
        row.status = "dismissed"
        row.resolved_by = user_id
        row.resolved_at = datetime.now(timezone.utc)
        await self._session.flush()
        return row


class DecisionRepository:
    """Phase 9 — audit history for human decisions on conflicts."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(
        self,
        *,
        conflict_id: str,
        project_id: str,
        resolver_id: str,
        option_index: int | None,
        custom_text: str | None,
        rationale: str,
        apply_actions: list,
        trace_id: str | None = None,
    ) -> DecisionRow:
        row = DecisionRow(
            id=_new_id(),
            conflict_id=conflict_id,
            project_id=project_id,
            resolver_id=resolver_id,
            option_index=option_index,
            custom_text=custom_text,
            rationale=rationale,
            apply_actions=apply_actions,
            apply_outcome="pending",
            apply_detail={},
            trace_id=trace_id,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def mark_applied(
        self,
        decision_id: str,
        *,
        outcome: str,
        detail: dict,
    ) -> DecisionRow | None:
        row = await self.get(decision_id)
        if row is None:
            return None
        row.apply_outcome = outcome
        row.apply_detail = detail
        row.applied_at = datetime.now(timezone.utc)
        await self._session.flush()
        return row

    async def get(self, decision_id: str) -> DecisionRow | None:
        return (
            await self._session.execute(
                select(DecisionRow).where(DecisionRow.id == decision_id)
            )
        ).scalar_one_or_none()

    async def list_for_conflict(self, conflict_id: str) -> list[DecisionRow]:
        stmt = (
            select(DecisionRow)
            .where(DecisionRow.conflict_id == conflict_id)
            .order_by(DecisionRow.created_at.desc())
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_for_project(
        self, project_id: str, *, limit: int = 100
    ) -> list[DecisionRow]:
        stmt = (
            select(DecisionRow)
            .where(DecisionRow.project_id == project_id)
            .order_by(DecisionRow.created_at.desc())
            .limit(limit)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def latest_for_conflict(self, conflict_id: str) -> DecisionRow | None:
        stmt = (
            select(DecisionRow)
            .where(DecisionRow.conflict_id == conflict_id)
            .order_by(DecisionRow.created_at.desc())
            .limit(1)
        )
        return (await self._session.execute(stmt)).scalar_one_or_none()


class DeliverySummaryRepository:
    """Phase 10 — append-only history of generated delivery summaries."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(
        self,
        *,
        project_id: str,
        requirement_version: int,
        content_json: dict,
        parse_outcome: str,
        qa_report: dict,
        prompt_version: str | None,
        trace_id: str | None,
        created_by: str | None,
    ) -> DeliverySummaryRow:
        row = DeliverySummaryRow(
            id=_new_id(),
            project_id=project_id,
            requirement_version=requirement_version,
            content_json=content_json,
            parse_outcome=parse_outcome,
            qa_report=qa_report,
            prompt_version=prompt_version,
            trace_id=trace_id,
            created_by=created_by,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def get(self, delivery_id: str) -> DeliverySummaryRow | None:
        return (
            await self._session.execute(
                select(DeliverySummaryRow).where(DeliverySummaryRow.id == delivery_id)
            )
        ).scalar_one_or_none()

    async def latest_for_project(
        self, project_id: str
    ) -> DeliverySummaryRow | None:
        stmt = (
            select(DeliverySummaryRow)
            .where(DeliverySummaryRow.project_id == project_id)
            .order_by(DeliverySummaryRow.created_at.desc())
            .limit(1)
        )
        return (await self._session.execute(stmt)).scalar_one_or_none()

    async def list_for_project(
        self, project_id: str, *, limit: int = 50
    ) -> list[DeliverySummaryRow]:
        stmt = (
            select(DeliverySummaryRow)
            .where(DeliverySummaryRow.project_id == project_id)
            .order_by(DeliverySummaryRow.created_at.desc())
            .limit(limit)
        )
        return list((await self._session.execute(stmt)).scalars().all())
