from __future__ import annotations

from datetime import datetime, timezone
from uuid import uuid4

from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from .orm import (
    AgentRunLogRow,
    AssignmentRow,
    ClarificationQuestionRow,
    CommentRow,
    CommitmentRow,
    ConflictRow,
    ConstraintRow,
    DecisionRow,
    DeliverableRow,
    DeliverySummaryRow,
    EventRow,
    GoalRow,
    IMSuggestionRow,
    IntakeEventRow,
    MembraneSignalRow,
    MessageRow,
    MilestoneRow,
    NotificationRow,
    ProjectMemberRow,
    ProjectRow,
    RequirementRow,
    RiskRow,
    RoutedSignalRow,
    SessionRow,
    StatusTransitionRow,
    StreamMemberRow,
    StreamRow,
    TaskDependencyRow,
    TaskRow,
    UserRow,
)


class DuplicateIntakeError(Exception):
    """Raised when (source, source_event_id) already exists."""

    def __init__(self, source: str, source_event_id: str, existing_project_id: str) -> None:
        super().__init__(
            f"intake already recorded: source={source} source_event_id={source_event_id}"
        )
        self.source = source
        self.source_event_id = source_event_id
        self.existing_project_id = existing_project_id


def _new_id() -> str:
    return str(uuid4())


class IntakeRepository:
    """Creates project+requirement+intake_event atomically, deduped by source key."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def find_existing(
        self, source: str, source_event_id: str
    ) -> IntakeEventRow | None:
        stmt = select(IntakeEventRow).where(
            IntakeEventRow.source == source,
            IntakeEventRow.source_event_id == source_event_id,
        )
        return (await self._session.execute(stmt)).scalar_one_or_none()

    async def create(
        self,
        *,
        source: str,
        source_event_id: str,
        title: str,
        raw_text: str,
        payload: dict,
    ) -> tuple[ProjectRow, RequirementRow, IntakeEventRow]:
        existing = await self.find_existing(source, source_event_id)
        if existing is not None:
            raise DuplicateIntakeError(source, source_event_id, existing.project_id)

        project = ProjectRow(id=_new_id(), title=title)
        requirement = RequirementRow(
            id=_new_id(), project_id=project.id, raw_text=raw_text, version=1
        )
        intake = IntakeEventRow(
            id=_new_id(),
            source=source,
            source_event_id=source_event_id,
            project_id=project.id,
            payload=payload,
        )
        self._session.add_all([project, requirement, intake])
        try:
            await self._session.flush()
        except IntegrityError as e:
            await self._session.rollback()
            # Race: another request wrote the same source_event_id between find + flush.
            fresh = await self.find_existing(source, source_event_id)
            if fresh is not None:
                raise DuplicateIntakeError(source, source_event_id, fresh.project_id) from e
            raise
        return project, requirement, intake


class RequirementRepository:
    """Reads + appends versioned requirement rows (Phase 4, decision 1E).

    v1 is written by IntakeRepository at intake time. v2+ is written by
    ClarificationService after a clarify-reply merges answers back into the
    requirement. Old versions are never mutated — event history stays intact.
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def latest_for_project(self, project_id: str) -> RequirementRow | None:
        stmt = (
            select(RequirementRow)
            .where(RequirementRow.project_id == project_id)
            .order_by(RequirementRow.version.desc())
            .limit(1)
        )
        return (await self._session.execute(stmt)).scalar_one_or_none()

    async def append_version(
        self,
        *,
        project_id: str,
        raw_text: str,
        parsed_json: dict | None = None,
        parse_outcome: str | None = None,
        parsed_at: datetime | None = None,
    ) -> RequirementRow:
        """Write the next version row. Caller sets parsed_* after agent runs."""
        latest = await self.latest_for_project(project_id)
        next_version = (latest.version + 1) if latest else 1
        row = RequirementRow(
            id=_new_id(),
            project_id=project_id,
            version=next_version,
            raw_text=raw_text,
            parsed_json=parsed_json,
            parse_outcome=parse_outcome,
            parsed_at=parsed_at,
        )
        self._session.add(row)
        await self._session.flush()
        return row


class ClarificationQuestionRepository:
    """Append questions generated by the ClarificationAgent; record answers.

    Questions are ordered within a requirement version via `position`. The
    (requirement_id, position) pair is unique, which also makes idempotent
    re-generation safe — callers can write in a single flush.
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def append_batch(
        self, *, requirement_id: str, questions: list[str]
    ) -> list[ClarificationQuestionRow]:
        rows: list[ClarificationQuestionRow] = []
        for idx, q in enumerate(questions):
            row = ClarificationQuestionRow(
                id=_new_id(),
                requirement_id=requirement_id,
                position=idx,
                question=q,
            )
            rows.append(row)
            self._session.add(row)
        await self._session.flush()
        return rows

    async def list_for_requirement(
        self, requirement_id: str
    ) -> list[ClarificationQuestionRow]:
        stmt = (
            select(ClarificationQuestionRow)
            .where(ClarificationQuestionRow.requirement_id == requirement_id)
            .order_by(ClarificationQuestionRow.position)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def get(self, question_id: str) -> ClarificationQuestionRow | None:
        stmt = select(ClarificationQuestionRow).where(
            ClarificationQuestionRow.id == question_id
        )
        return (await self._session.execute(stmt)).scalar_one_or_none()

    async def record_answer(
        self, *, question_id: str, answer: str
    ) -> ClarificationQuestionRow | None:
        row = await self.get(question_id)
        if row is None:
            return None
        row.answer = answer
        row.answered_at = datetime.now(timezone.utc)
        await self._session.flush()
        return row

    async def unanswered_count(self, requirement_id: str) -> int:
        rows = await self.list_for_requirement(requirement_id)
        return sum(1 for r in rows if r.answer is None)


class ProjectGraphRepository:
    """Reads + appends Goal/Deliverable/Constraint/Risk rows per requirement version.

    Per decision 1E, each requirement version owns its own set of graph entities.
    v2's entities are written alongside v2 (not by mutating v1's rows). The
    "latest graph" for stage derivation is the entities bound to the latest
    requirement version. Old versions stay as history.

    append_for_requirement is idempotent — a second call for the same
    requirement_id is a no-op that returns the existing rows. Callers force
    regeneration by promoting to a new requirement version, not by rewriting.
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def _list(
        self, model, requirement_id: str
    ) -> list:
        stmt = (
            select(model)
            .where(model.requirement_id == requirement_id)
            .order_by(model.sort_order)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_goals(self, requirement_id: str) -> list[GoalRow]:
        return await self._list(GoalRow, requirement_id)

    async def list_deliverables(self, requirement_id: str) -> list[DeliverableRow]:
        return await self._list(DeliverableRow, requirement_id)

    async def list_constraints(self, requirement_id: str) -> list[ConstraintRow]:
        return await self._list(ConstraintRow, requirement_id)

    async def list_risks(self, requirement_id: str) -> list[RiskRow]:
        return await self._list(RiskRow, requirement_id)

    async def list_all(
        self, requirement_id: str
    ) -> dict[str, list]:
        return {
            "goals": await self.list_goals(requirement_id),
            "deliverables": await self.list_deliverables(requirement_id),
            "constraints": await self.list_constraints(requirement_id),
            "risks": await self.list_risks(requirement_id),
        }

    async def has_entities(self, requirement_id: str) -> bool:
        """Cheap existence check used by stage derivation."""
        for model in (GoalRow, DeliverableRow, ConstraintRow, RiskRow):
            stmt = select(model.id).where(model.requirement_id == requirement_id).limit(1)
            if (await self._session.execute(stmt)).scalar_one_or_none() is not None:
                return True
        return False

    async def append_for_requirement(
        self,
        *,
        project_id: str,
        requirement_id: str,
        goals: list[dict],
        deliverables: list[dict],
        constraints: list[dict],
        risks: list[dict],
    ) -> dict[str, list]:
        """Write the graph for a requirement version. Idempotent per requirement.

        Each entity dict carries type-specific fields:
          goal: {title, description?, success_criteria?}
          deliverable: {title, kind?}
          constraint: {kind, content, severity?}
          risk: {title, content?, severity?}
        """
        if await self.has_entities(requirement_id):
            return await self.list_all(requirement_id)

        created: dict[str, list] = {
            "goals": [],
            "deliverables": [],
            "constraints": [],
            "risks": [],
        }
        for idx, g in enumerate(goals):
            row = GoalRow(
                id=_new_id(),
                project_id=project_id,
                requirement_id=requirement_id,
                sort_order=idx,
                title=g["title"],
                description=g.get("description", ""),
                success_criteria=g.get("success_criteria"),
            )
            self._session.add(row)
            created["goals"].append(row)
        for idx, d in enumerate(deliverables):
            row = DeliverableRow(
                id=_new_id(),
                project_id=project_id,
                requirement_id=requirement_id,
                sort_order=idx,
                title=d["title"],
                kind=d.get("kind", "feature"),
            )
            self._session.add(row)
            created["deliverables"].append(row)
        for idx, c in enumerate(constraints):
            row = ConstraintRow(
                id=_new_id(),
                project_id=project_id,
                requirement_id=requirement_id,
                sort_order=idx,
                kind=c["kind"],
                content=c["content"],
                severity=c.get("severity", "medium"),
            )
            self._session.add(row)
            created["constraints"].append(row)
        for idx, r in enumerate(risks):
            row = RiskRow(
                id=_new_id(),
                project_id=project_id,
                requirement_id=requirement_id,
                sort_order=idx,
                title=r["title"],
                content=r.get("content", ""),
                severity=r.get("severity", "medium"),
            )
            self._session.add(row)
            created["risks"].append(row)
        await self._session.flush()
        return created


class PlanRepository:
    """Append + list Tasks / Dependencies / Milestones for a requirement version.

    Idempotent per requirement_id — a second append call for a requirement
    that already has tasks is a no-op. Callers promote the requirement
    version to force a rebuild.

    DAG invariants (orphan-deliverable detection, cycle detection) live in
    PlanningService — this repository is pure storage. It does own the
    minimal helpers needed to feed detection (task_refs_for_requirement,
    edge_set_for_requirement).
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def list_tasks(self, requirement_id: str) -> list[TaskRow]:
        stmt = (
            select(TaskRow)
            .where(TaskRow.requirement_id == requirement_id)
            .order_by(TaskRow.sort_order)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_dependencies(
        self, requirement_id: str
    ) -> list[TaskDependencyRow]:
        stmt = (
            select(TaskDependencyRow)
            .where(TaskDependencyRow.requirement_id == requirement_id)
            .order_by(TaskDependencyRow.created_at)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_milestones(self, requirement_id: str) -> list[MilestoneRow]:
        stmt = (
            select(MilestoneRow)
            .where(MilestoneRow.requirement_id == requirement_id)
            .order_by(MilestoneRow.sort_order)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_all(self, requirement_id: str) -> dict[str, list]:
        return {
            "tasks": await self.list_tasks(requirement_id),
            "dependencies": await self.list_dependencies(requirement_id),
            "milestones": await self.list_milestones(requirement_id),
        }

    async def has_plan(self, requirement_id: str) -> bool:
        stmt = (
            select(TaskRow.id)
            .where(TaskRow.requirement_id == requirement_id)
            .limit(1)
        )
        return (await self._session.execute(stmt)).scalar_one_or_none() is not None

    async def append_plan(
        self,
        *,
        project_id: str,
        requirement_id: str,
        tasks: list[dict],
        dependencies: list[dict],
        milestones: list[dict],
    ) -> dict[str, list]:
        """Persist a validated plan. Idempotent per requirement.

        Caller responsibilities (PlanningService enforces):
          - task dicts carry a local `ref` for dependency resolution; this
            repository maps `ref` → generated id internally.
          - dependency dicts use `from_ref`/`to_ref`; cycle detection already
            ran.
          - every task.deliverable_ref is null or a valid deliverable id for
            this requirement (orphan check already ran).
        """
        if await self.has_plan(requirement_id):
            return await self.list_all(requirement_id)

        ref_to_id: dict[str, str] = {}
        task_rows: list[TaskRow] = []
        for idx, t in enumerate(tasks):
            row_id = _new_id()
            ref_to_id[t["ref"]] = row_id
            row = TaskRow(
                id=row_id,
                project_id=project_id,
                requirement_id=requirement_id,
                sort_order=idx,
                deliverable_id=t.get("deliverable_id"),
                title=t["title"],
                description=t.get("description", ""),
                assignee_role=t.get("assignee_role", "unknown"),
                estimate_hours=t.get("estimate_hours"),
                acceptance_criteria=t.get("acceptance_criteria"),
            )
            self._session.add(row)
            task_rows.append(row)

        dep_rows: list[TaskDependencyRow] = []
        for d in dependencies:
            from_id = ref_to_id[d["from_ref"]]
            to_id = ref_to_id[d["to_ref"]]
            row = TaskDependencyRow(
                id=_new_id(),
                requirement_id=requirement_id,
                from_task_id=from_id,
                to_task_id=to_id,
            )
            self._session.add(row)
            dep_rows.append(row)

        milestone_rows: list[MilestoneRow] = []
        for idx, m in enumerate(milestones):
            related_ids = [ref_to_id[r] for r in m.get("related_task_refs", []) if r in ref_to_id]
            row = MilestoneRow(
                id=_new_id(),
                project_id=project_id,
                requirement_id=requirement_id,
                sort_order=idx,
                title=m["title"],
                target_date=m.get("target_date"),
                related_task_ids=related_ids or None,
            )
            self._session.add(row)
            milestone_rows.append(row)

        await self._session.flush()
        return {
            "tasks": task_rows,
            "dependencies": dep_rows,
            "milestones": milestone_rows,
        }


class EventRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def append(
        self, *, name: str, trace_id: str | None, payload: dict
    ) -> EventRow:
        # Surface project_id onto the column so Phase 7' SSE can filter without
        # JSON queries. Keeps the payload dict unchanged for downstream readers.
        project_id = payload.get("project_id") if isinstance(payload, dict) else None
        row = EventRow(
            id=_new_id(),
            name=name,
            trace_id=trace_id,
            payload=payload,
            project_id=project_id,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def list_by_name(self, name: str) -> list[EventRow]:
        stmt = select(EventRow).where(EventRow.name == name).order_by(EventRow.created_at)
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_for_trace(self, trace_id: str) -> list[EventRow]:
        stmt = (
            select(EventRow)
            .where(EventRow.trace_id == trace_id)
            .order_by(EventRow.created_at)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_for_project_since(
        self, project_id: str, since_id: str | None = None, limit: int = 100
    ) -> list[EventRow]:
        """Ordered by created_at. Cursor via `since_id` (exclusive)."""
        stmt = select(EventRow).where(EventRow.project_id == project_id)
        if since_id is not None:
            since = (
                await self._session.execute(
                    select(EventRow).where(EventRow.id == since_id)
                )
            ).scalar_one_or_none()
            if since is not None:
                stmt = stmt.where(EventRow.created_at > since.created_at)
        stmt = stmt.order_by(EventRow.created_at).limit(limit)
        return list((await self._session.execute(stmt)).scalars().all())


class AgentRunLogRepository:
    """Writes one row per LLM agent call — decision 2C2."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def append(
        self,
        *,
        agent: str,
        prompt_version: str,
        outcome: str,
        attempts: int,
        latency_ms: int,
        prompt_tokens: int,
        completion_tokens: int,
        cache_read_tokens: int,
        project_id: str | None = None,
        trace_id: str | None = None,
        error: str | None = None,
    ) -> AgentRunLogRow:
        row = AgentRunLogRow(
            id=_new_id(),
            agent=agent,
            prompt_version=prompt_version,
            project_id=project_id,
            trace_id=trace_id,
            outcome=outcome,
            attempts=attempts,
            latency_ms=latency_ms,
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            cache_read_tokens=cache_read_tokens,
            error=error,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def list_for_agent(self, agent: str) -> list[AgentRunLogRow]:
        stmt = (
            select(AgentRunLogRow)
            .where(AgentRunLogRow.agent == agent)
            .order_by(AgentRunLogRow.created_at)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_since(
        self,
        *,
        since: datetime | None = None,
        agent: str | None = None,
        limit: int = 500,
    ) -> list[AgentRunLogRow]:
        """Return rows created at or after `since`, optionally filtered by agent."""
        stmt = select(AgentRunLogRow)
        if since is not None:
            stmt = stmt.where(AgentRunLogRow.created_at >= since)
        if agent is not None:
            stmt = stmt.where(AgentRunLogRow.agent == agent)
        stmt = stmt.order_by(AgentRunLogRow.created_at.desc()).limit(limit)
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_for_trace(self, trace_id: str) -> list[AgentRunLogRow]:
        stmt = (
            select(AgentRunLogRow)
            .where(AgentRunLogRow.trace_id == trace_id)
            .order_by(AgentRunLogRow.created_at)
        )
        return list((await self._session.execute(stmt)).scalars().all())


# ---- Phase 7' auth + Phase 7'' collab repositories ----------------------


class UserRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(
        self,
        *,
        username: str,
        password_hash: str,
        password_salt: str,
        display_name: str = "",
    ) -> UserRow:
        row = UserRow(
            id=_new_id(),
            username=username,
            password_hash=password_hash,
            password_salt=password_salt,
            display_name=display_name or username,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def get(self, user_id: str) -> UserRow | None:
        return (
            await self._session.execute(select(UserRow).where(UserRow.id == user_id))
        ).scalar_one_or_none()

    async def get_by_username(self, username: str) -> UserRow | None:
        return (
            await self._session.execute(
                select(UserRow).where(UserRow.username == username)
            )
        ).scalar_one_or_none()

    async def list_all(self, limit: int = 50) -> list[UserRow]:
        stmt = select(UserRow).order_by(UserRow.created_at).limit(limit)
        return list((await self._session.execute(stmt)).scalars().all())

    async def update_profile(
        self,
        user_id: str,
        *,
        declared_abilities: list[str] | None = None,
        role_hints: list[str] | None = None,
        signal_tally: dict[str, int] | None = None,
        display_language: str | None = None,
    ) -> UserRow | None:
        """Partial update of response-profile fields + display_language.

        None values mean "leave untouched" — the router translates an
        unset key into None. Keys present with empty lists clear that key.
        Per north-star §"Profile as first-class primitive", profile is a
        JSON dict so callers shape their own keys; we merge at the top level.
        """
        row = await self.get(user_id)
        if row is None:
            return None
        profile = dict(row.profile or {})
        if declared_abilities is not None:
            profile["declared_abilities"] = list(declared_abilities)
        if role_hints is not None:
            profile["role_hints"] = list(role_hints)
        if signal_tally is not None:
            profile["signal_tally"] = dict(signal_tally)
        row.profile = profile
        if display_language is not None:
            row.display_language = display_language
        await self._session.flush()
        return row


class SessionRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(
        self, *, token: str, user_id: str, expires_at: datetime
    ) -> SessionRow:
        row = SessionRow(token=token, user_id=user_id, expires_at=expires_at)
        self._session.add(row)
        await self._session.flush()
        return row

    async def get(self, token: str) -> SessionRow | None:
        return (
            await self._session.execute(
                select(SessionRow).where(SessionRow.token == token)
            )
        ).scalar_one_or_none()

    async def delete(self, token: str) -> None:
        row = await self.get(token)
        if row is not None:
            await self._session.delete(row)
            await self._session.flush()


class ProjectMemberRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def add(
        self, *, project_id: str, user_id: str, role: str = "member"
    ) -> ProjectMemberRow:
        existing = (
            await self._session.execute(
                select(ProjectMemberRow).where(
                    ProjectMemberRow.project_id == project_id,
                    ProjectMemberRow.user_id == user_id,
                )
            )
        ).scalar_one_or_none()
        if existing is not None:
            return existing
        row = ProjectMemberRow(
            id=_new_id(), project_id=project_id, user_id=user_id, role=role
        )
        self._session.add(row)
        try:
            await self._session.flush()
        except IntegrityError:
            await self._session.rollback()
            existing = (
                await self._session.execute(
                    select(ProjectMemberRow).where(
                        ProjectMemberRow.project_id == project_id,
                        ProjectMemberRow.user_id == user_id,
                    )
                )
            ).scalar_one()
            return existing
        return row

    async def list_for_project(self, project_id: str) -> list[ProjectMemberRow]:
        stmt = (
            select(ProjectMemberRow)
            .where(ProjectMemberRow.project_id == project_id)
            .order_by(ProjectMemberRow.created_at)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_for_user(self, user_id: str) -> list[ProjectMemberRow]:
        stmt = (
            select(ProjectMemberRow)
            .where(ProjectMemberRow.user_id == user_id)
            .order_by(ProjectMemberRow.created_at.desc())
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def is_member(self, project_id: str, user_id: str) -> bool:
        row = (
            await self._session.execute(
                select(ProjectMemberRow).where(
                    ProjectMemberRow.project_id == project_id,
                    ProjectMemberRow.user_id == user_id,
                )
            )
        ).scalar_one_or_none()
        return row is not None


class AssignmentRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def set_assignment(
        self, *, project_id: str, task_id: str, user_id: str | None
    ) -> AssignmentRow | None:
        """Replace any active assignment for task_id. `user_id=None` unassigns."""
        stmt = select(AssignmentRow).where(
            AssignmentRow.task_id == task_id, AssignmentRow.active == True  # noqa: E712
        )
        active = list((await self._session.execute(stmt)).scalars().all())
        now = datetime.now(timezone.utc)
        for row in active:
            row.active = False
            row.resolved_at = now

        if user_id is None:
            await self._session.flush()
            return None

        row = AssignmentRow(
            id=_new_id(),
            project_id=project_id,
            task_id=task_id,
            user_id=user_id,
            active=True,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def active_for_task(self, task_id: str) -> AssignmentRow | None:
        stmt = select(AssignmentRow).where(
            AssignmentRow.task_id == task_id, AssignmentRow.active == True  # noqa: E712
        )
        return (await self._session.execute(stmt)).scalar_one_or_none()

    async def list_for_project(self, project_id: str) -> list[AssignmentRow]:
        stmt = (
            select(AssignmentRow)
            .where(
                AssignmentRow.project_id == project_id,
                AssignmentRow.active == True,  # noqa: E712
            )
            .order_by(AssignmentRow.created_at)
        )
        return list((await self._session.execute(stmt)).scalars().all())


class CommentRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def append(
        self,
        *,
        project_id: str,
        author_id: str,
        target_kind: str,
        target_id: str,
        body: str,
        parent_comment_id: str | None = None,
    ) -> CommentRow:
        row = CommentRow(
            id=_new_id(),
            project_id=project_id,
            author_id=author_id,
            target_kind=target_kind,
            target_id=target_id,
            body=body,
            parent_comment_id=parent_comment_id,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def list_for_target(
        self, target_kind: str, target_id: str
    ) -> list[CommentRow]:
        stmt = (
            select(CommentRow)
            .where(
                CommentRow.target_kind == target_kind,
                CommentRow.target_id == target_id,
            )
            .order_by(CommentRow.created_at)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_for_project(self, project_id: str) -> list[CommentRow]:
        stmt = (
            select(CommentRow)
            .where(CommentRow.project_id == project_id)
            .order_by(CommentRow.created_at)
        )
        return list((await self._session.execute(stmt)).scalars().all())


class MessageRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def append(
        self,
        *,
        project_id: str | None,
        author_id: str,
        body: str,
        stream_id: str | None = None,
        kind: str = "text",
        linked_id: str | None = None,
    ) -> MessageRow:
        row = MessageRow(
            id=_new_id(),
            project_id=project_id,
            author_id=author_id,
            body=body,
            stream_id=stream_id,
            kind=kind,
            linked_id=linked_id,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def list_recent(
        self, project_id: str, limit: int = 100
    ) -> list[MessageRow]:
        stmt = (
            select(MessageRow)
            .where(MessageRow.project_id == project_id)
            .order_by(MessageRow.created_at.desc())
            .limit(limit)
        )
        rows = list((await self._session.execute(stmt)).scalars().all())
        rows.reverse()
        return rows

    async def list_for_stream(
        self, stream_id: str, limit: int = 100
    ) -> list[MessageRow]:
        stmt = (
            select(MessageRow)
            .where(MessageRow.stream_id == stream_id)
            .order_by(MessageRow.created_at.desc())
            .limit(limit)
        )
        rows = list((await self._session.execute(stmt)).scalars().all())
        rows.reverse()
        return rows


class IMSuggestionRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def append(
        self,
        *,
        project_id: str,
        message_id: str,
        kind: str,
        confidence: float,
        targets: list | None,
        proposal: dict | None,
        reasoning: str,
        prompt_version: str | None,
        outcome: str,
        attempts: int,
        counter_of_id: str | None = None,
    ) -> IMSuggestionRow:
        row = IMSuggestionRow(
            id=_new_id(),
            project_id=project_id,
            message_id=message_id,
            kind=kind,
            confidence=confidence,
            targets=targets,
            proposal=proposal,
            reasoning=reasoning,
            prompt_version=prompt_version,
            outcome=outcome,
            attempts=attempts,
            counter_of_id=counter_of_id,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def get(self, suggestion_id: str) -> IMSuggestionRow | None:
        return (
            await self._session.execute(
                select(IMSuggestionRow).where(IMSuggestionRow.id == suggestion_id)
            )
        ).scalar_one_or_none()

    # Alias kept for plan-doc fidelity; callers use either name.
    async def get_by_id(self, suggestion_id: str) -> IMSuggestionRow | None:
        return await self.get(suggestion_id)

    async def get_for_message(self, message_id: str) -> IMSuggestionRow | None:
        return (
            await self._session.execute(
                select(IMSuggestionRow).where(
                    IMSuggestionRow.message_id == message_id
                )
            )
        ).scalar_one_or_none()

    async def resolve(self, suggestion_id: str, status: str) -> IMSuggestionRow | None:
        row = await self.get(suggestion_id)
        if row is None:
            return None
        row.status = status
        row.resolved_at = datetime.now(timezone.utc)
        await self._session.flush()
        return row

    async def mark_countered(self, suggestion_id: str) -> IMSuggestionRow | None:
        """Flip `status` to 'countered' + stamp resolved_at — signal-chain."""
        return await self.resolve(suggestion_id, "countered")

    async def mark_escalated(self, suggestion_id: str) -> IMSuggestionRow | None:
        """Flip `status` to 'escalated', set escalation_state='requested'."""
        row = await self.get(suggestion_id)
        if row is None:
            return None
        row.status = "escalated"
        row.escalation_state = "requested"
        row.resolved_at = datetime.now(timezone.utc)
        await self._session.flush()
        return row

    async def set_decision_id(
        self, suggestion_id: str, decision_id: str
    ) -> IMSuggestionRow | None:
        """Link the suggestion to the DecisionRow that crystallized from it."""
        row = await self.get(suggestion_id)
        if row is None:
            return None
        row.decision_id = decision_id
        await self._session.flush()
        return row


class NotificationRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def append(
        self,
        *,
        user_id: str,
        project_id: str,
        kind: str,
        body: str,
        target_kind: str | None = None,
        target_id: str | None = None,
    ) -> NotificationRow:
        row = NotificationRow(
            id=_new_id(),
            user_id=user_id,
            project_id=project_id,
            kind=kind,
            body=body,
            target_kind=target_kind,
            target_id=target_id,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def list_for_user(
        self, user_id: str, *, unread_only: bool = False, limit: int = 50
    ) -> list[NotificationRow]:
        stmt = select(NotificationRow).where(NotificationRow.user_id == user_id)
        if unread_only:
            stmt = stmt.where(NotificationRow.read == False)  # noqa: E712
        stmt = stmt.order_by(NotificationRow.created_at.desc()).limit(limit)
        return list((await self._session.execute(stmt)).scalars().all())

    async def unread_count(self, user_id: str) -> int:
        stmt = select(NotificationRow.id).where(
            NotificationRow.user_id == user_id,
            NotificationRow.read == False,  # noqa: E712
        )
        return len(list((await self._session.execute(stmt)).scalars().all()))

    async def mark_read(self, notification_id: str, user_id: str) -> NotificationRow | None:
        row = (
            await self._session.execute(
                select(NotificationRow).where(
                    NotificationRow.id == notification_id,
                    NotificationRow.user_id == user_id,
                )
            )
        ).scalar_one_or_none()
        if row is None:
            return None
        row.read = True
        await self._session.flush()
        return row

    async def mark_all_read(self, user_id: str) -> int:
        rows = await self.list_for_user(user_id, unread_only=True, limit=500)
        for r in rows:
            r.read = True
        await self._session.flush()
        return len(rows)


class ConflictRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def upsert(
        self,
        *,
        project_id: str,
        requirement_id: str | None,
        rule: str,
        severity: str,
        fingerprint: str,
        targets: list,
        detail: dict,
        trace_id: str | None = None,
    ) -> tuple[ConflictRow, bool]:
        """Insert a new conflict or reopen an existing one by fingerprint.

        Returns (row, is_new). A dismissed/resolved conflict that matches on
        fingerprint is NOT reopened — the user's decision stands. Only `open`
        or `stale` rows are refreshed.
        """
        existing = (
            await self._session.execute(
                select(ConflictRow).where(
                    ConflictRow.project_id == project_id,
                    ConflictRow.fingerprint == fingerprint,
                )
            )
        ).scalar_one_or_none()
        if existing is not None:
            if existing.status in ("open", "stale"):
                existing.status = "open"
                existing.severity = severity
                existing.targets = targets
                existing.detail = detail
                existing.requirement_id = requirement_id
                if trace_id:
                    existing.trace_id = trace_id
                await self._session.flush()
            return existing, False

        row = ConflictRow(
            id=_new_id(),
            project_id=project_id,
            requirement_id=requirement_id,
            rule=rule,
            severity=severity,
            fingerprint=fingerprint,
            targets=targets,
            detail=detail,
            trace_id=trace_id,
            status="open",
            explanation_outcome="pending",
        )
        self._session.add(row)
        await self._session.flush()
        return row, True

    async def attach_explanation(
        self,
        conflict_id: str,
        *,
        summary: str,
        options: list,
        prompt_version: str,
        outcome: str,
    ) -> ConflictRow | None:
        row = await self.get(conflict_id)
        if row is None:
            return None
        row.summary = summary
        row.options = options
        row.explanation_prompt_version = prompt_version
        row.explanation_outcome = outcome
        await self._session.flush()
        return row

    async def get(self, conflict_id: str) -> ConflictRow | None:
        return (
            await self._session.execute(
                select(ConflictRow).where(ConflictRow.id == conflict_id)
            )
        ).scalar_one_or_none()

    async def list_for_project(
        self,
        project_id: str,
        *,
        include_closed: bool = False,
    ) -> list[ConflictRow]:
        stmt = select(ConflictRow).where(ConflictRow.project_id == project_id)
        if not include_closed:
            stmt = stmt.where(ConflictRow.status == "open")
        stmt = stmt.order_by(
            ConflictRow.severity.desc(),  # "high" > "medium" > "low" alphabetically? see service for ordering map
            ConflictRow.created_at.desc(),
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_open_fingerprints(self, project_id: str) -> set[str]:
        stmt = select(ConflictRow.fingerprint).where(
            ConflictRow.project_id == project_id,
            ConflictRow.status == "open",
        )
        return set((await self._session.execute(stmt)).scalars().all())

    async def mark_stale(self, project_id: str, keep: set[str]) -> int:
        """Flip any open conflict whose fingerprint isn't in `keep` to stale.

        Called at the end of a detection pass so the UI can gray out conflicts
        that the current rules no longer fire on, without losing the history.
        """
        rows = list(
            (
                await self._session.execute(
                    select(ConflictRow).where(
                        ConflictRow.project_id == project_id,
                        ConflictRow.status == "open",
                    )
                )
            )
            .scalars()
            .all()
        )
        n = 0
        for r in rows:
            if r.fingerprint not in keep:
                r.status = "stale"
                n += 1
        if n:
            await self._session.flush()
        return n

    async def resolve(
        self,
        conflict_id: str,
        *,
        user_id: str,
        option_index: int | None,
    ) -> ConflictRow | None:
        row = await self.get(conflict_id)
        if row is None:
            return None
        row.status = "resolved"
        row.resolved_by = user_id
        row.resolved_option_index = option_index
        row.resolved_at = datetime.now(timezone.utc)
        await self._session.flush()
        return row

    async def dismiss(
        self, conflict_id: str, *, user_id: str
    ) -> ConflictRow | None:
        row = await self.get(conflict_id)
        if row is None:
            return None
        row.status = "dismissed"
        row.resolved_by = user_id
        row.resolved_at = datetime.now(timezone.utc)
        await self._session.flush()
        return row


class DecisionRepository:
    """Phase 9 — audit history for human decisions on conflicts."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(
        self,
        *,
        conflict_id: str | None,
        project_id: str,
        resolver_id: str,
        option_index: int | None,
        custom_text: str | None,
        rationale: str,
        apply_actions: list,
        trace_id: str | None = None,
        source_suggestion_id: str | None = None,
        apply_outcome: str = "pending",
        apply_detail: dict | None = None,
    ) -> DecisionRow:
        """Persist a decision.

        `conflict_id` is now optional because IM-originated decisions crystallize
        from a suggestion directly (vision §6, signal-chain). In that case the
        caller passes `source_suggestion_id` instead. `apply_outcome`/`apply_detail`
        can be set at create-time for synchronous crystallization.
        """
        row = DecisionRow(
            id=_new_id(),
            conflict_id=conflict_id,
            project_id=project_id,
            resolver_id=resolver_id,
            option_index=option_index,
            custom_text=custom_text,
            rationale=rationale,
            apply_actions=apply_actions,
            apply_outcome=apply_outcome,
            apply_detail=apply_detail or {},
            trace_id=trace_id,
            source_suggestion_id=source_suggestion_id,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def mark_applied(
        self,
        decision_id: str,
        *,
        outcome: str,
        detail: dict,
    ) -> DecisionRow | None:
        row = await self.get(decision_id)
        if row is None:
            return None
        row.apply_outcome = outcome
        row.apply_detail = detail
        row.applied_at = datetime.now(timezone.utc)
        await self._session.flush()
        return row

    async def get(self, decision_id: str) -> DecisionRow | None:
        return (
            await self._session.execute(
                select(DecisionRow).where(DecisionRow.id == decision_id)
            )
        ).scalar_one_or_none()

    async def list_for_conflict(self, conflict_id: str) -> list[DecisionRow]:
        stmt = (
            select(DecisionRow)
            .where(DecisionRow.conflict_id == conflict_id)
            .order_by(DecisionRow.created_at.desc())
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_for_project(
        self, project_id: str, *, limit: int = 100
    ) -> list[DecisionRow]:
        stmt = (
            select(DecisionRow)
            .where(DecisionRow.project_id == project_id)
            .order_by(DecisionRow.created_at.desc())
            .limit(limit)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def latest_for_conflict(self, conflict_id: str) -> DecisionRow | None:
        stmt = (
            select(DecisionRow)
            .where(DecisionRow.conflict_id == conflict_id)
            .order_by(DecisionRow.created_at.desc())
            .limit(1)
        )
        return (await self._session.execute(stmt)).scalar_one_or_none()


class DeliverySummaryRepository:
    """Phase 10 — append-only history of generated delivery summaries."""

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(
        self,
        *,
        project_id: str,
        requirement_version: int,
        content_json: dict,
        parse_outcome: str,
        qa_report: dict,
        prompt_version: str | None,
        trace_id: str | None,
        created_by: str | None,
    ) -> DeliverySummaryRow:
        row = DeliverySummaryRow(
            id=_new_id(),
            project_id=project_id,
            requirement_version=requirement_version,
            content_json=content_json,
            parse_outcome=parse_outcome,
            qa_report=qa_report,
            prompt_version=prompt_version,
            trace_id=trace_id,
            created_by=created_by,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def get(self, delivery_id: str) -> DeliverySummaryRow | None:
        return (
            await self._session.execute(
                select(DeliverySummaryRow).where(DeliverySummaryRow.id == delivery_id)
            )
        ).scalar_one_or_none()

    async def latest_for_project(
        self, project_id: str
    ) -> DeliverySummaryRow | None:
        stmt = (
            select(DeliverySummaryRow)
            .where(DeliverySummaryRow.project_id == project_id)
            .order_by(DeliverySummaryRow.created_at.desc())
            .limit(1)
        )
        return (await self._session.execute(stmt)).scalar_one_or_none()

    async def list_for_project(
        self, project_id: str, *, limit: int = 50
    ) -> list[DeliverySummaryRow]:
        stmt = (
            select(DeliverySummaryRow)
            .where(DeliverySummaryRow.project_id == project_id)
            .order_by(DeliverySummaryRow.created_at.desc())
            .limit(limit)
        )
        return list((await self._session.execute(stmt)).scalars().all())


# ---- Phase B (v2) — stream repositories ---------------------------------


class StreamRepository:
    """Stream CRUD. Project streams are created once per project via boot
    backfill; DM streams are created on-demand with 1:1 dedup.
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(
        self,
        *,
        type: str,
        project_id: str | None = None,
        owner_user_id: str | None = None,
    ) -> StreamRow:
        row = StreamRow(
            id=_new_id(),
            type=type,
            project_id=project_id,
            owner_user_id=owner_user_id,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def get(self, stream_id: str) -> StreamRow | None:
        return (
            await self._session.execute(
                select(StreamRow).where(StreamRow.id == stream_id)
            )
        ).scalar_one_or_none()

    async def get_for_project(self, project_id: str) -> StreamRow | None:
        stmt = select(StreamRow).where(
            StreamRow.project_id == project_id,
            StreamRow.type == "project",
        )
        return (await self._session.execute(stmt)).scalar_one_or_none()

    async def get_personal_for_user_in_project(
        self, *, user_id: str, project_id: str
    ) -> StreamRow | None:
        """Phase L — the one personal stream a user has inside a project.

        Expected unique in (project_id, owner_user_id, type='personal'), but
        no DB-level UNIQUE constraint enforces it yet and race conditions
        during seeding have produced duplicates in the wild. Use `.first()`
        instead of `scalar_one_or_none()` so the API can't throw
        `MultipleResultsFound` on degraded data — prefer the oldest row for
        stability.
        """
        stmt = (
            select(StreamRow)
            .where(
                StreamRow.project_id == project_id,
                StreamRow.owner_user_id == user_id,
                StreamRow.type == "personal",
            )
            .order_by(StreamRow.created_at)
            .limit(1)
        )
        return (await self._session.execute(stmt)).scalars().first()

    async def find_dm_between(
        self, user_a: str, user_b: str
    ) -> StreamRow | None:
        """Find the canonical DM stream between two users.

        Dedup key is the set of member user_ids — any DM stream whose
        members == {user_a, user_b} counts. We scan via StreamMemberRow
        rather than storing a composite key because 1:1 DMs are the only
        case in v1 (group streams are v2).
        """
        a_streams = (
            await self._session.execute(
                select(StreamMemberRow.stream_id).where(
                    StreamMemberRow.user_id == user_a
                )
            )
        ).scalars().all()
        if not a_streams:
            return None
        stmt = select(StreamRow).where(
            StreamRow.id.in_(list(a_streams)),
            StreamRow.type == "dm",
        )
        candidates = list((await self._session.execute(stmt)).scalars().all())
        for stream in candidates:
            members = (
                await self._session.execute(
                    select(StreamMemberRow.user_id).where(
                        StreamMemberRow.stream_id == stream.id
                    )
                )
            ).scalars().all()
            if set(members) == {user_a, user_b}:
                return stream
        return None

    async def list_for_user(self, user_id: str) -> list[StreamRow]:
        """Streams the user belongs to, sorted by last_activity_at desc."""
        stmt = (
            select(StreamRow)
            .join(StreamMemberRow, StreamMemberRow.stream_id == StreamRow.id)
            .where(StreamMemberRow.user_id == user_id)
            .order_by(StreamRow.last_activity_at.desc())
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def touch_activity(self, stream_id: str) -> StreamRow | None:
        row = await self.get(stream_id)
        if row is None:
            return None
        row.last_activity_at = datetime.now(timezone.utc)
        await self._session.flush()
        return row


class StreamMemberRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def add(
        self,
        *,
        stream_id: str,
        user_id: str,
        role_in_stream: str = "member",
    ) -> StreamMemberRow:
        existing = (
            await self._session.execute(
                select(StreamMemberRow).where(
                    StreamMemberRow.stream_id == stream_id,
                    StreamMemberRow.user_id == user_id,
                )
            )
        ).scalar_one_or_none()
        if existing is not None:
            return existing
        row = StreamMemberRow(
            id=_new_id(),
            stream_id=stream_id,
            user_id=user_id,
            role_in_stream=role_in_stream,
        )
        self._session.add(row)
        try:
            await self._session.flush()
        except IntegrityError:
            await self._session.rollback()
            return (
                await self._session.execute(
                    select(StreamMemberRow).where(
                        StreamMemberRow.stream_id == stream_id,
                        StreamMemberRow.user_id == user_id,
                    )
                )
            ).scalar_one()
        return row

    async def list_for_stream(self, stream_id: str) -> list[StreamMemberRow]:
        stmt = (
            select(StreamMemberRow)
            .where(StreamMemberRow.stream_id == stream_id)
            .order_by(StreamMemberRow.joined_at)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def is_member(self, stream_id: str, user_id: str) -> bool:
        row = (
            await self._session.execute(
                select(StreamMemberRow).where(
                    StreamMemberRow.stream_id == stream_id,
                    StreamMemberRow.user_id == user_id,
                )
            )
        ).scalar_one_or_none()
        return row is not None

    async def get_member(
        self, stream_id: str, user_id: str
    ) -> StreamMemberRow | None:
        return (
            await self._session.execute(
                select(StreamMemberRow).where(
                    StreamMemberRow.stream_id == stream_id,
                    StreamMemberRow.user_id == user_id,
                )
            )
        ).scalar_one_or_none()

    async def mark_read(
        self, *, stream_id: str, user_id: str
    ) -> StreamMemberRow | None:
        row = await self.get_member(stream_id, user_id)
        if row is None:
            return None
        row.last_read_at = datetime.now(timezone.utc)
        await self._session.flush()
        return row

    async def unread_count(
        self, *, stream_id: str, user_id: str
    ) -> int:
        """Count messages in the stream authored strictly after my
        last_read_at. If last_read_at is null (never read), every message
        counts; but we don't count my own messages as unread-to-me.
        """
        member = await self.get_member(stream_id, user_id)
        if member is None:
            return 0
        stmt = select(MessageRow.id).where(MessageRow.stream_id == stream_id)
        if member.last_read_at is not None:
            stmt = stmt.where(MessageRow.created_at > member.last_read_at)
        stmt = stmt.where(MessageRow.author_id != user_id)
        rows = (await self._session.execute(stmt)).scalars().all()
        return len(list(rows))


# ---- Phase L — routed signal repository ---------------------------------


class RoutedSignalRepository:
    """Phase L — persistence for cross-user sub-agent routed signals.

    North-star §"Routing primitive (data model)". A signal is created when
    RoutingService.dispatch runs; it stores the source's framing, the
    background snippets, the rich option set the target's edge-agent will
    render, and ultimately the target's reply. Status transitions:
      pending → replied → (accepted | declined | expired)
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(
        self,
        *,
        source_user_id: str,
        target_user_id: str,
        source_stream_id: str,
        target_stream_id: str,
        framing: str,
        background: list,
        options: list,
        project_id: str | None = None,
        trace_id: str | None = None,
    ) -> RoutedSignalRow:
        row = RoutedSignalRow(
            id=_new_id(),
            trace_id=trace_id,
            source_user_id=source_user_id,
            target_user_id=target_user_id,
            source_stream_id=source_stream_id,
            target_stream_id=target_stream_id,
            project_id=project_id,
            framing=framing,
            background_json=list(background or []),
            options_json=list(options or []),
            status="pending",
            reply_json=None,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def get(self, signal_id: str) -> RoutedSignalRow | None:
        return (
            await self._session.execute(
                select(RoutedSignalRow).where(RoutedSignalRow.id == signal_id)
            )
        ).scalar_one_or_none()

    async def list_for_user(
        self,
        user_id: str,
        *,
        kind: str,
        status: str | None = None,
        limit: int = 100,
    ) -> list[RoutedSignalRow]:
        """`kind` in {'inbound', 'outbound'}. Optional `status` filter."""
        if kind == "inbound":
            stmt = select(RoutedSignalRow).where(
                RoutedSignalRow.target_user_id == user_id
            )
        elif kind == "outbound":
            stmt = select(RoutedSignalRow).where(
                RoutedSignalRow.source_user_id == user_id
            )
        else:
            raise ValueError(f"kind must be 'inbound' or 'outbound', got {kind!r}")
        if status is not None:
            stmt = stmt.where(RoutedSignalRow.status == status)
        stmt = stmt.order_by(RoutedSignalRow.created_at.desc()).limit(limit)
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_for_dm(
        self, user_a_id: str, user_b_id: str, *, limit: int = 100
    ) -> list[RoutedSignalRow]:
        """Routed signals in either direction between two users."""
        stmt = (
            select(RoutedSignalRow)
            .where(
                (
                    (RoutedSignalRow.source_user_id == user_a_id)
                    & (RoutedSignalRow.target_user_id == user_b_id)
                )
                | (
                    (RoutedSignalRow.source_user_id == user_b_id)
                    & (RoutedSignalRow.target_user_id == user_a_id)
                )
            )
            .order_by(RoutedSignalRow.created_at.desc())
            .limit(limit)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def mark_replied(
        self,
        signal_id: str,
        *,
        option_id: str | None,
        custom_text: str | None,
    ) -> RoutedSignalRow | None:
        """Record target's reply + flip status to 'replied'. Idempotent: a
        second reply overwrites the first — v1 routing is not a multi-turn
        conversation, so latest-reply-wins is acceptable.
        """
        row = await self.get(signal_id)
        if row is None:
            return None
        now = datetime.now(timezone.utc)
        row.status = "replied"
        row.reply_json = {
            "option_id": option_id,
            "custom_text": custom_text,
            "responded_at": now.isoformat(),
        }
        row.responded_at = now
        await self._session.flush()
        return row


# ---- Phase D — membrane signal repository -------------------------------


class MembraneSignalRepository:
    """Phase D — persistence for membrane-ingested external signals.

    Vision §5.12 (Membranes). Dedup key is (project_id, source_identifier).
    Re-ingesting the same URL / commit hash / forum post returns the
    existing row; the caller never double-classifies.

    Status transitions: pending-review → (approved | rejected | routed).
    `rejected` rows stay as audit history, never routed.
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def find_by_source(
        self, *, project_id: str | None, source_identifier: str
    ) -> MembraneSignalRow | None:
        stmt = select(MembraneSignalRow).where(
            MembraneSignalRow.source_identifier == source_identifier,
        )
        # NULL-safe project scope match — project-scoped dedup only collides
        # with rows from the same project_id value (including null↔null).
        if project_id is None:
            stmt = stmt.where(MembraneSignalRow.project_id.is_(None))
        else:
            stmt = stmt.where(MembraneSignalRow.project_id == project_id)
        return (await self._session.execute(stmt)).scalar_one_or_none()

    async def create(
        self,
        *,
        project_id: str | None,
        source_kind: str,
        source_identifier: str,
        raw_content: str,
        ingested_by_user_id: str | None = None,
        trace_id: str | None = None,
    ) -> MembraneSignalRow:
        row = MembraneSignalRow(
            id=_new_id(),
            project_id=project_id,
            source_kind=source_kind,
            source_identifier=source_identifier,
            raw_content=raw_content,
            ingested_by_user_id=ingested_by_user_id,
            classification_json={},
            status="pending-review",
            trace_id=trace_id,
        )
        self._session.add(row)
        try:
            await self._session.flush()
        except IntegrityError:
            # Race: another request wrote the same (project_id, source_identifier)
            # between find + flush. Return the existing row instead of exploding.
            await self._session.rollback()
            fresh = await self.find_by_source(
                project_id=project_id, source_identifier=source_identifier
            )
            if fresh is not None:
                return fresh
            raise
        return row

    async def get(self, signal_id: str) -> MembraneSignalRow | None:
        return (
            await self._session.execute(
                select(MembraneSignalRow).where(MembraneSignalRow.id == signal_id)
            )
        ).scalar_one_or_none()

    async def set_classification(
        self,
        signal_id: str,
        *,
        classification: dict,
        status: str,
    ) -> MembraneSignalRow | None:
        row = await self.get(signal_id)
        if row is None:
            return None
        row.classification_json = dict(classification)
        row.status = status
        await self._session.flush()
        return row

    async def mark_status(
        self,
        signal_id: str,
        *,
        status: str,
        approved_by_user_id: str | None = None,
    ) -> MembraneSignalRow | None:
        row = await self.get(signal_id)
        if row is None:
            return None
        row.status = status
        if approved_by_user_id is not None:
            row.approved_by_user_id = approved_by_user_id
            row.approved_at = datetime.now(timezone.utc)
        await self._session.flush()
        return row

    async def list_for_project(
        self,
        project_id: str,
        *,
        status: str | None = None,
        limit: int = 100,
    ) -> list[MembraneSignalRow]:
        stmt = select(MembraneSignalRow).where(
            MembraneSignalRow.project_id == project_id
        )
        if status is not None:
            stmt = stmt.where(MembraneSignalRow.status == status)
        stmt = stmt.order_by(MembraneSignalRow.created_at.desc()).limit(limit)
        return list((await self._session.execute(stmt)).scalars().all())


# ---- Sprint 1b — status transition log (time-cursor replay) -------------


class StatusTransitionRepository:
    """Append-only log of graph-entity status mutations.

    Every status flip on a task / risk / deliverable / goal / milestone /
    constraint / decision writes a row here. `GET /projects/{id}/graph-at`
    replays the log to reconstruct the status of each entity at a past
    timestamp. Writes are cheap (one INSERT per mutation) and the replay
    query is `project_id + changed_at <= ts` — both indexed.

    `record` is a helper that services call after they flip a status. It
    accepts `old_status` explicitly rather than reading it back from the
    row because most service call sites already have the previous value in
    hand (they just read it before writing), and a separate read would
    double the query count on the hot path.
    """

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def record(
        self,
        *,
        project_id: str,
        entity_kind: str,
        entity_id: str,
        old_status: str | None,
        new_status: str,
        changed_by_user_id: str | None = None,
        trace_id: str | None = None,
        changed_at: datetime | None = None,
    ) -> StatusTransitionRow:
        row = StatusTransitionRow(
            id=_new_id(),
            project_id=project_id,
            entity_kind=entity_kind,
            entity_id=entity_id,
            old_status=old_status,
            new_status=new_status,
            changed_by_user_id=changed_by_user_id,
            trace_id=trace_id,
            changed_at=changed_at or datetime.now(timezone.utc),
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def list_for_project_up_to(
        self, project_id: str, *, upto: datetime
    ) -> list[StatusTransitionRow]:
        """All transitions on or before `upto`, ordered oldest → newest.

        Ordering matters for replay: the LATEST transition wins per entity.
        A consumer iterates forwards and overwrites a running map so the
        final map carries the most recent status per entity.
        """
        stmt = (
            select(StatusTransitionRow)
            .where(
                StatusTransitionRow.project_id == project_id,
                StatusTransitionRow.changed_at <= upto,
            )
            .order_by(StatusTransitionRow.changed_at)
        )
        return list((await self._session.execute(stmt)).scalars().all())

    async def list_for_project_since(
        self, project_id: str, *, since: datetime, limit: int = 500
    ) -> list[StatusTransitionRow]:
        """Recent transitions after `since`, oldest → newest, capped.

        Used by the web timeline strip to render event markers.
        """
        stmt = (
            select(StatusTransitionRow)
            .where(
                StatusTransitionRow.project_id == project_id,
                StatusTransitionRow.changed_at > since,
            )
            .order_by(StatusTransitionRow.changed_at)
            .limit(limit)
        )
        return list((await self._session.execute(stmt)).scalars().all())


class CommitmentRepository:
    """CRUD + listing for CommitmentRow (Sprint 2a).

    Invariants the service layer relies on:
      * `headline` is effectively immutable — callers mark a commitment
        `withdrawn` and create a new row instead of editing. This
        keeps the timeline of promises legible.
      * Only terminal-state transitions touch `resolved_at`. Non-
        terminal updates (re-anchoring scope_ref) do not — the create
        timestamp remains the canonical "when was this promised."
    """

    _TERMINAL_STATUSES = frozenset({"met", "missed", "withdrawn"})

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def create(
        self,
        *,
        project_id: str,
        created_by_user_id: str,
        headline: str,
        owner_user_id: str | None = None,
        target_date: datetime | None = None,
        metric: str | None = None,
        scope_ref_kind: str | None = None,
        scope_ref_id: str | None = None,
        source_message_id: str | None = None,
    ) -> CommitmentRow:
        row = CommitmentRow(
            id=_new_id(),
            project_id=project_id,
            created_by_user_id=created_by_user_id,
            owner_user_id=owner_user_id or created_by_user_id,
            headline=headline,
            target_date=target_date,
            metric=metric,
            scope_ref_kind=scope_ref_kind,
            scope_ref_id=scope_ref_id,
            source_message_id=source_message_id,
        )
        self._session.add(row)
        await self._session.flush()
        return row

    async def get(self, commitment_id: str) -> CommitmentRow | None:
        return (
            await self._session.execute(
                select(CommitmentRow).where(CommitmentRow.id == commitment_id)
            )
        ).scalar_one_or_none()

    async def list_for_project(
        self,
        project_id: str,
        *,
        status: str | None = None,
        limit: int = 100,
    ) -> list[CommitmentRow]:
        stmt = select(CommitmentRow).where(CommitmentRow.project_id == project_id)
        if status is not None:
            stmt = stmt.where(CommitmentRow.status == status)
        stmt = stmt.order_by(CommitmentRow.created_at.desc()).limit(limit)
        return list((await self._session.execute(stmt)).scalars().all())

    async def set_status(
        self,
        commitment_id: str,
        *,
        status: str,
    ) -> CommitmentRow | None:
        """Update the commitment's status. Setting a terminal state
        (met/missed/withdrawn) stamps `resolved_at`; reverting to open
        clears it. Unknown status strings raise ValueError at the
        service boundary — this layer stays permissive so seed/migration
        data doesn't get rejected."""
        row = await self.get(commitment_id)
        if row is None:
            return None
        row.status = status
        if status in self._TERMINAL_STATUSES:
            row.resolved_at = datetime.now(timezone.utc)
        else:
            row.resolved_at = None
        await self._session.flush()
        return row
