"""Bounded-context ORM package (H4 split). Re-exports every Row + the
shared Base/mixins so `from workgraph_persistence.orm import X` and the
alembic side-effect `import workgraph_persistence.orm` keep working.
Importing this package imports every submodule, registering all mappers
on the single shared Base."""
from ._base import Base, _FrecencyColumnsMixin, _GraphEntityBase, _utcnow
from .core import (
    ProjectRow,
    UserRow,
    SessionRow,
    ProjectMemberRow,
    OrganizationRow,
    OrganizationMemberRow,
    OnboardingStateRow,
    EventRow,
    AgentRunLogRow,
    IntakeEventRow,
)
from .graph_plan import (
    RequirementRow,
    ClarificationQuestionRow,
    GoalRow,
    DeliverableRow,
    ConstraintRow,
    RiskRow,
    TaskRow,
    TaskDependencyRow,
    MilestoneRow,
    AssignmentRow,
    TaskStatusUpdateRow,
    TaskScoreRow,
    StatusTransitionRow,
)
from .streams_im import (
    StreamRow,
    StreamMemberRow,
    MessageRow,
    IMSuggestionRow,
    CommentRow,
    NotificationRow,
    RoutedSignalRow,
)
from .decisions import (
    ConflictRow,
    DecisionRow,
    GatedProposalRow,
    VoteRow,
    DissentRow,
    ScrimmageRow,
    SilentConsensusRow,
    DeliverySummaryRow,
)
from .kb_membrane import (
    KbFolderRow,
    KbItemRow,
    KbItemLicenseRow,
    MembraneSubscriptionRow,
    MeetingTranscriptRow,
)
from .commitments import (
    CommitmentRow,
    HandoffRow,
    LicenseAuditRow,
)

__all__ = [
    "Base",
    "AgentRunLogRow",
    "AssignmentRow",
    "ClarificationQuestionRow",
    "CommentRow",
    "CommitmentRow",
    "ConflictRow",
    "ConstraintRow",
    "DecisionRow",
    "DeliverableRow",
    "DeliverySummaryRow",
    "DissentRow",
    "EventRow",
    "GatedProposalRow",
    "GoalRow",
    "HandoffRow",
    "IMSuggestionRow",
    "IntakeEventRow",
    "KbFolderRow",
    "KbItemLicenseRow",
    "KbItemRow",
    "LicenseAuditRow",
    "MeetingTranscriptRow",
    "MembraneSubscriptionRow",
    "MessageRow",
    "MilestoneRow",
    "NotificationRow",
    "OnboardingStateRow",
    "OrganizationMemberRow",
    "OrganizationRow",
    "ProjectMemberRow",
    "ProjectRow",
    "RequirementRow",
    "RiskRow",
    "RoutedSignalRow",
    "ScrimmageRow",
    "SessionRow",
    "SilentConsensusRow",
    "StatusTransitionRow",
    "StreamMemberRow",
    "StreamRow",
    "TaskDependencyRow",
    "TaskRow",
    "TaskScoreRow",
    "TaskStatusUpdateRow",
    "UserRow",
    "VoteRow",
]
